import { gql, useQuery } from "@apollo/client";
import { ArrowUpRight, Package, ShoppingBag, TriangleAlert, ClipboardList, Image, ShieldCheck } from "lucide-react";
import type { AuthUser } from "@vital-forge/shared-logic";
import { canEditCatalog, type Section } from "../../components/layout/navigation";
import { BusinessDashboard } from "../business/BusinessDashboard";
const HOME = gql`query StaffHome { staffHome }`;
type HomeData = { activeProducts: number; persistence: string; missingProducts: Array<{ id: string; title: string }>; lowStock: Array<{ productId: string; title: string; sku: string; stock: number }>; pendingPayment: number; reviewOrders: { totalCount: number; orders: Array<{ id?: string; _id?: string; orderNumber: string; customer: { fullName: string } }> } | null; pendingPurchases: Array<{ id: string; number: string }>; expiringLots: Array<{ sku: string; lot: string; expiresOn: string; quantity: number }>; failures: { total: number } | null; updatedAt: string };
export function HomePanel({ user, onNavigate, onCreate }: { user: AuthUser; onNavigate: (section: Section, search?: string) => void; onCreate: () => void }) {
  const { data, loading, error, refetch } = useQuery<{ staffHome: HomeData }>(HOME, { fetchPolicy: "network-only" }); const home = data?.staffHome;
  const stockAllowed = user.role !== "CATALOG";
  return <section className="home-panel"><div className="welcome-banner"><div><span className="eyebrow">TU CENTRO DE TRABAJO</span><h1>Buen día, {user.name.split(" ")[0]}.</h1><p>Estos son los pendientes que necesitan tu atención.</p></div><div className="welcome-actions"><button onClick={() => void refetch()}>Actualizar</button>{canEditCatalog(user.role) && <button className="primary-button" onClick={onCreate}>Crear producto <ArrowUpRight size={16}/></button>}</div></div>
    {["ADMIN", "MANAGER"].includes(user.role) && <BusinessDashboard compact readonly={user.role!=="ADMIN"} onNavigate={onNavigate}/>}
    {loading && <p role="status">Revisando pendientes…</p>}{error && <div role="alert" className="inline-error">{error.message}</div>}
    {home && <>{home.persistence === "demo" && <p className="demo-banner" role="status">Modo de demostración: los datos se guardan en memoria y se pierden al reiniciar la API.</p>}<div className="metric-grid home-metrics"><button className="metric" onClick={() => onNavigate("products")}><Package/><span>Productos activos</span><strong>{home.activeProducts}</strong><small>Abrir catálogo →</small></button><button className="metric" onClick={() => onNavigate("products", "")}><Image/><span>Fichas sin foto o categoría</span><strong>{home.missingProducts.length}</strong><small>Completar catálogo →</small></button>{stockAllowed && <><button className="metric" onClick={() => onNavigate("inventory")}><TriangleAlert/><span>Variantes bajo mínimo</span><strong>{home.lowStock.length}</strong><small>Revisar reposición →</small></button><button className="metric" onClick={() => onNavigate("orders", "status:PAYMENT_REVIEW")}><ShoppingBag/><span>Pagos por revisar</span><strong>{home.reviewOrders?.totalCount ?? 0}</strong><small>Revisar pedidos →</small></button></>}</div>
    <div className="home-columns"><article className="report-card"><div className="card-title"><h2>Prioridades de hoy</h2><span className="status-tag">Acciones directas</span></div>{stockAllowed && <><button className="task-row" onClick={() => onNavigate("orders", "status:PENDING_PAYMENT")}><ShoppingBag/><span><b>{home.pendingPayment} pedidos pendientes de pago</b><small>Consulta el detalle y revisa las referencias recibidas.</small></span><ArrowUpRight/></button><button className="task-row" onClick={() => onNavigate("purchases", "status:ORDERED")}><ClipboardList/><span><b>{home.pendingPurchases.length} compras por recibir</b><small>Registra la recepción para actualizar el inventario.</small></span><ArrowUpRight/></button><button className="task-row" onClick={() => onNavigate("warehouses")}><TriangleAlert/><span><b>{home.expiringLots.length} lotes vencidos o próximos a vencer</b><small>Revisa las existencias con vencimiento dentro de 30 días.</small></span><ArrowUpRight/></button></>}{home.failures && <button className="task-row" onClick={() => onNavigate("audit", "status:FAILED")}><ShieldCheck/><span><b>{home.failures.total} operaciones fallidas en 24 horas</b><small>Revisa el motivo y el registro afectado.</small></span><ArrowUpRight/></button>}{!stockAllowed && <p>Completa las fichas pendientes y revisa las fotografías antes de publicar.</p>}</article>
    <article className="report-card"><div className="card-title"><h2>Catálogo por completar</h2><button onClick={() => onNavigate("products")}>Ver catálogo</button></div>{home.missingProducts.slice(0, 8).map((p) => <button className="task-row" key={p.id} onClick={() => onNavigate("products", p.title)}><Package/><span><b>{p.title}</b><small>Faltan fotografías o clasificación</small></span><ArrowUpRight/></button>)}{!home.missingProducts.length && <div className="empty-state"><ShieldCheck/><b>Catálogo al día</b><p>Todos los productos activos tienen foto y categoría.</p></div>}</article></div>
    {stockAllowed && home.lowStock.length > 0 && <article className="report-card"><div className="card-title"><h2>Reposición prioritaria</h2><button onClick={() => onNavigate("inventory")}>Ver todo el inventario</button></div>{home.lowStock.slice(0, 5).map((p) => <button className="task-row" key={`${p.productId}:${p.sku}`} onClick={() => onNavigate("inventory", p.sku)}><Package/><span><b>{p.title}</b><small>{p.sku}</small></span><span className="stock-warning">{p.stock} disponibles</span></button>)}</article>}
    <p className="updated-note">Actualizado {new Date(home.updatedAt).toLocaleString("es-EC", { timeZone: "America/Guayaquil" })}</p></>}
  </section>;
}
