import { usePanelFilter } from "../lib/usePanelRoute";
import { useLeaveGuard, useUnsavedChanges } from "./common/UnsavedChanges";
import { gql, useMutation, useQuery } from "@apollo/client";
import { useRef, useState } from "react";
import { formatMoney } from "@vital-forge/ui-core";

const DASHBOARD = gql`query Management($filters: JSON!) { managementDashboard(filters: $filters) }`;
const INVENTORY = gql`query Inventory($filters: JSON!) { managementDashboard: inventoryOverview(filters: $filters) }`;
const ADJUST = gql`mutation AdjustStock($input: JSON!) { adjustStock(input: $input) }`;
type InventoryRow = { productId: string; title: string; sku: string; flavor: string; stock: number; availableStock: number; expiredStock: number; reorderPoint: number; units: number; dailyUnits: number; coverage: number | null; suggestedOrder: number; low: boolean; inTransit: number; arrivingInTime: number; averageStock: number | null; turnover: number | null; historyComplete: boolean };
type Comparison = { revenue: number; units: number; revenueChange: number | null };
type Dashboard = { margin: { grossProfit: number | null; percent: number | null; coveragePercent: number }; comparison: { previousMonth: Comparison | null; previousYear: Comparison }; revenue: number; units: number; orderCount: number; averageTicket: number; lowStock: number; outOfStock: number; noSales: number; stockValue: number; elapsedDays: number; ranking: Array<{ productId: string; title: string; units: number; revenue: number }>; months: Array<{ month: number; units: number; revenue: number }>; categories: Array<{ name: string; units: number; revenue: number }>; inventory: InventoryRow[] };
const TAXONOMY = gql`query ManagementCategories { taxonomy { categories { key name } } }`;
export function exportCsv(name: string, rows: unknown[][]) {
  const encode = (v: unknown) => { let value = String(v ?? ""); if (/^[=+@\-\t\r]/.test(value)) value = `'${value}`; return `"${value.replace(/"/g, '""')}"`; };
  const url = URL.createObjectURL(new Blob(["\uFEFF" + rows.map((row) => row.map(encode).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" }));
  const link = document.createElement("a"); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export function ManagementPanel({ inventoryOnly = false, readonly = false, initialSearch = "" }: { inventoryOnly?: boolean; readonly?: boolean; initialSearch?: string }) {
  const [year, setYear] = usePanelFilter("year",new Date().getFullYear());
  const [month, setMonth] = usePanelFilter("month",new Date().getMonth() + 1);
  const [category, setCategory] = usePanelFilter("category","");
  const [coverageDays, setCoverageDays] = usePanelFilter("coverage",30);
  const [search, setSearch] = usePanelFilter("q",initialSearch);
  const [dateBasis, setDateBasis] = usePanelFilter("basis","CREATED");
  const [sort,setSort] = usePanelFilter("sort","priority");
  const [lowOnly, setLowOnly] = usePanelFilter("low",false);
  const [page, setPage] = usePanelFilter("page",0);
  const [edit, setEdit] = useState<InventoryRow | null>(null);
  const [delta, setDelta] = useState(0);
  const [point, setPoint] = useState(5);
  const [reason, setReason] = useState("");
  const [message, setMessage] = useState("");
  const saving=useRef(false);const [busy,setBusy]=useState(false);
  const query = useQuery<{ managementDashboard: Dashboard }>(inventoryOnly ? INVENTORY : DASHBOARD, { variables: { filters: { year, month, category, coverageDays, dateBasis } }, fetchPolicy: "network-only" });
  const taxonomy = useQuery<{ taxonomy: { categories: Array<{ key: string; name: string }> } }>(TAXONOMY);
  const [adjust, mutation] = useMutation(ADJUST);
  const leave=useLeaveGuard();
  useUnsavedChanges(Boolean(edit&&(delta!==0||point!==edit.reorderPoint||reason)),{busy:busy||mutation.loading});
  const data = query.data?.managementDashboard;
  const rows = (data?.inventory ?? []).filter((v) => (!lowOnly || v.low) && `${v.title} ${v.sku} ${v.flavor}`.toLowerCase().includes(search.toLowerCase())).sort((a,b) => sort === "units" ? b.units-a.units : sort === "turnover" ? (b.turnover ?? -1)-(a.turnover ?? -1) : Number(b.low)-Number(a.low) || b.suggestedOrder-a.suggestedOrder);
  const resetPage = () => setPage(0);
  return <section className="admin-section management">
    <div className="section-heading"><div><span className="kicker">{inventoryOnly ? "Administración / Existencias" : "Gerencia / Resultados"}</span><h1>{inventoryOnly ? "Inventario y reposición" : "Ventas y desempeño"}</h1><p>{inventoryOnly ? "Control por SKU, mínimos y ajustes con motivo obligatorio." : "Analiza productos, categorías y velocidad de venta por período."}</p></div><button className="preview" onClick={() => {setMessage("");void query.refetch().catch(error=>setMessage(error instanceof Error?error.message:"No se pudo actualizar"));}}>Actualizar</button></div>
    <div className="filter-bar">
      <label>Año<input aria-label="Año" type="number" min="2020" max="2100" value={year} onChange={(e) => { const n = Number(e.target.value); if (n >= 2020 && n <= 2100) { setYear(n); resetPage(); } }} /></label>
      <label>Período<select value={month} onChange={(e) => { setMonth(Number(e.target.value)); resetPage(); }}><option value={0}>Todo el año</option>{Array.from({ length: 12 }, (_, i) => <option key={i} value={i + 1}>{new Date(2026, i, 1).toLocaleString("es", { month: "long" })}</option>)}</select></label>
      <label>Categoría<select value={category} onChange={(e) => { setCategory(e.target.value); resetPage(); }}><option value="">Todas las categorías</option>{taxonomy.data?.taxonomy.categories.map((c) => <option key={c.key} value={c.key}>{c.name}</option>)}</select></label>
      {!inventoryOnly && <label>Fecha de venta<select value={dateBasis} onChange={e=>setDateBasis(e.target.value)}><option value="CREATED">Creación del pedido</option><option value="PAID">Confirmación del pago</option></select></label>}
      <label>Días a cubrir<select value={coverageDays} onChange={(e) => setCoverageDays(Number(e.target.value))}>{[7, 15, 30, 60, 90].map((n) => <option key={n} value={n}>{n} días</option>)}</select></label>
    </div>
    {message&&<p role="status" className="admin-alert">{message}</p>}{query.loading && <p role="status">Calculando indicadores…</p>}{query.error && <p className="admin-alert" role="alert">{query.error.message}</p>}
    {data && <>
      <div className="metric-grid">{(inventoryOnly ? [["Unidades disponibles", data.inventory.reduce((s, v) => s + v.availableStock, 0)], ["SKU bajo mínimo", data.lowStock], ["SKU agotados", data.outOfStock], ["SKU sin ventas en período", data.noSales]] : [["Ventas de productos", formatMoney(data.revenue)], ["Unidades vendidas", data.units], ["Pedidos pagados", data.orderCount], ["Ticket de productos", formatMoney(data.averageTicket)]]).map(([label, value]) => <article className="metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
      {!inventoryOnly && <><p className="method-note">Pedidos PAID, PREPARING, SHIPPED y COMPLETED, según {dateBasis === "CREATED" ? "fecha de creación" : "fecha de confirmación del pago registrada; pedidos antiguos sin fecha de pago quedan excluidos"} (Ecuador UTC−5). Valores de productos sin envío; pendientes, cancelados y devueltos excluidos. En categorías múltiples los grupos no son sumables.</p>
      <div className="metric-grid comparison-grid">{[["Mes anterior",data.comparison.previousMonth],["Año anterior",data.comparison.previousYear]].map(([label,raw])=>{const c=raw as Comparison|null;return <article className="metric" key={String(label)}><span>{String(label)}</span><strong>{c?formatMoney(c.revenue):"No aplica"}</strong><small>{c?.revenueChange==null?"Sin base para calcular variación":`${c.revenueChange>0?"+":""}${c.revenueChange}% frente al período comparable`}</small></article>;})}<article className="metric"><span>Margen bruto con costo registrado</span><strong>{data.margin.grossProfit===null?"Sin datos":formatMoney(data.margin.grossProfit)}</strong><small>{data.margin.percent===null?"Registra costos en compras":`${data.margin.percent}% · costos conocidos en ${data.margin.coveragePercent}% de las ventas`}</small></article></div><p className="method-note">Comparaciones con igual cantidad de días transcurridos, hasta el cierre del período anterior. El margen cubre únicamente líneas con costo conocido y no incluye gastos operativos.</p>
      <div className="report-grid"><article className="report-card"><h2>Ventas mensuales · {year}</h2><div className="bar-chart" aria-label="Ventas por mes">{data.months.map((m) => <button type="button" key={m.month} className="bar-column" aria-label={`Ver mes ${m.month}`} onClick={()=>setMonth(m.month)}><span>{formatMoney(m.revenue)}</span><div className="bar-track"><i style={{ height: `${m.revenue ? Math.max(2, m.revenue / Math.max(...data.months.map((x) => x.revenue), 1) * 100) : 0}%` }} /></div><small>{new Date(year, m.month - 1, 1).toLocaleString("es", { month: "short" })}</small></button>)}</div></article>
      <article className="report-card"><h2>Ventas por categoría</h2>{!data.categories.length && <p>Sin ventas pagadas en este período.</p>}{data.categories.map((c) => <div className="rank-line" key={c.name}><span>{c.name}<small>{c.units} unidades</small></span><b>{formatMoney(c.revenue)}</b></div>)}</article></div>
      <article className="report-card"><div className="section-heading"><h2>Productos más vendidos</h2><button onClick={() => exportCsv(`ventas-${year}-${month}.csv`, [["Producto", "Unidades", "Ventas"], ...data.ranking.map((p) => [p.title, p.units, p.revenue])])}>Exportar CSV</button></div>{!data.ranking.length && <p>No hay ventas pagadas para los filtros elegidos.</p>}{data.ranking.slice(0, 20).map((p, i) => <div className="rank-line" key={p.productId}><span><b>{i + 1}.</b> {p.title}</span><span>{p.units} unidades · <b>{formatMoney(p.revenue)}</b> <button onClick={()=>{setSearch(p.title);setPage(0);document.getElementById("sku-report")?.scrollIntoView({behavior:"smooth"});}}>Ver variantes</button></span></div>)}</article></>}
      <article className="report-card" id="sku-report"><div className="section-heading"><div><h2>{inventoryOnly ? "Existencias por variante" : "Velocidad de venta y compras sugeridas"}</h2><p>Valor del stock a precio de venta: {formatMoney(data.stockValue)}.</p></div><button onClick={() => exportCsv(`inventario-${year}-${month}.csv`, [["Producto", "SKU", "Stock", "Mínimo", "Vendidas", "Unidades por día", "Días cobertura", "En tránsito", "Llega en plazo", "Pedir", "Stock promedio", "Rotación física"], ...rows.map((v) => [v.title, v.sku, v.stock, v.reorderPoint, v.units, v.dailyUnits, v.coverage, v.inTransit, v.arrivingInTime, v.suggestedOrder, v.averageStock, v.turnover])])}>Exportar CSV</button></div>
      <div className="filter-bar"><label>Buscar<input placeholder="Producto o SKU" value={search} onChange={(e) => { setSearch(e.target.value); resetPage(); }} /></label><label>Ordenar<select value={sort} onChange={e=>{setSort(e.target.value);setPage(0);}}><option value="priority">Prioridad de reposición</option><option value="units">Más vendidos</option><option value="turnover">Mayor rotación</option></select></label><label className="checkbox-label"><input type="checkbox" checked={lowOnly} onChange={(e) => { setLowOnly(e.target.checked); resetPage(); }} />Solo bajo mínimo</label></div>
      <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Producto / SKU</th><th>Stock / disponible</th><th>Mínimo</th><th>Vendidas</th><th>Unid./día</th><th>Cobertura</th><th>En tránsito</th><th>Pedir</th><th>Rotación física</th>{inventoryOnly && !readonly && <th>Acción</th>}</tr></thead><tbody>{rows.slice(page * 30, (page + 1) * 30).map((v) => <tr key={`${v.productId}:${v.sku}`}><td><b>{v.title}</b><small>{v.sku} · {v.flavor}</small></td><td><span className={v.low ? "stock-warning" : ""}>{v.stock}</span>{v.expiredStock>0&&<small>{v.availableStock} disponibles · {v.expiredStock} vencidas</small>}</td><td>{v.reorderPoint}</td><td>{v.units}</td><td>{v.dailyUnits}</td><td>{v.coverage === null ? "Sin demanda" : `${v.coverage} días`}</td><td>{v.inTransit}<small>{v.arrivingInTime} en plazo</small></td><td>{v.suggestedOrder}</td><td title={v.averageStock === null ? "Falta historial de inventario para este período" : `Stock promedio: ${v.averageStock}`}>{v.turnover === null ? "Sin base histórica" : `${v.turnover} veces`}</td>{inventoryOnly && !readonly && <td><button onClick={async () => { if(!await leave())return; setEdit(v); setDelta(0); setPoint(v.reorderPoint); setReason(""); setMessage(""); }}>Ajustar</button></td>}</tr>)}</tbody></table></div>{!rows.length && <p>No hay variantes para estos filtros.</p>}
      <div className="pagination"><button disabled={!page} onClick={() => setPage(page - 1)}>Anterior</button><span>{rows.length} variantes · Página {page + 1}</span><button disabled={(page + 1) * 30 >= rows.length} onClick={() => setPage(page + 1)}>Siguiente</button></div>
      <p className="method-note">Velocidad = unidades vendidas / {data.elapsedDays} días transcurridos del período. Cobertura = stock actual / velocidad. Compra sugerida: cubre la demanda estimada para {coverageDays} días y el mínimo, descontando stock y solo compras con llegada prevista dentro de la cobertura. Las compras atrasadas, sin fecha o posteriores al horizonte no reducen la sugerencia. Rotación física = unidades vendidas / stock registrado promedio ponderado por tiempo; se muestra solo con historial suficiente y no equivale a rotación contable.</p></article>
    </>}
    {edit && <div className="editor-inline report-card"><h2>Ajustar {edit.sku}</h2><form onSubmit={async (e) => { e.preventDefault();if(saving.current)return;saving.current=true;setBusy(true);setMessage("");try { await adjust({ variables: { input: { productId: edit.productId, sku: edit.sku, expectedStock: edit.stock, delta, reorderPoint: point, reason } } }); setEdit(null);setMessage("Ajuste guardado.");await query.refetch().catch(()=>setMessage("Ajuste guardado. Actualiza para ver los últimos datos.")); } catch (error) { setMessage(error instanceof Error ? error.message : "Error al ajustar"); } finally{saving.current=false;setBusy(false);} }}><fieldset disabled={busy} style={{border:0,padding:0,margin:0,minWidth:0}}><div className="fields two"><label>Entrada (+) / salida (−)<input type="number" required min={-edit.stock} max={100000} value={delta} onChange={(e) => setDelta(Number(e.target.value))} /></label><label>Stock mínimo<input type="number" required min={0} max={100000} value={point} onChange={(e) => setPoint(Number(e.target.value))} /></label><label className="full">Motivo<textarea required minLength={5} maxLength={300} value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Conteo físico o corrección de mínimo…" /></label></div><p>Stock sin reservar: {edit.stock} → {edit.stock + delta}. Para corregir una bodega o lote concreto, utiliza Bodegas y lotes. Registra las recepciones desde Órdenes de compra.</p><button className="publish" disabled={busy||mutation.loading}>Guardar ajuste</button> <button type="button" onClick={async () => {if(await leave())setEdit(null);}}>Cancelar</button></fieldset></form></div>}
  </section>;
}
