import { useUnsavedChanges, useLeaveGuard } from "./common/UnsavedChanges";
import { usePanelFilter } from "../lib/usePanelRoute";
import { gql, useApolloClient, useMutation, useQuery } from "@apollo/client";
import { useEffect, useRef, useState, type ReactNode } from "react";
import type { AuthUser, Product } from "@vital-forge/shared-logic";
import { useImageQueue } from "./ImageUploadQueue";
import { MEDIA_URL } from "../lib/uploadImage";
import { roleLabels, type Section } from "./layout/navigation";
import { useConfirm } from "./common/ConfirmDialog";
const ACCOUNTS = gql`query Accounts($filters: JSON) { accounts(filters: $filters) }`;
const RESET_TWO_FACTOR = gql`mutation ResetTwoFactor($id: ID!) { resetTwoFactor(id: $id) }`;
const SAVE = gql`mutation SaveAccount($id: ID, $input: JSON!) { saveAccount(id: $id, input: $input) { id name email role status } }`;
const RECORDS = gql`query Records($entity: String!, $filters: JSON) { databaseRecords(entity: $entity, filters: $filters) }`;
const RENAME = gql`mutation RenameMedia($id: ID!, $label: String!) { renameMedia(id: $id, label: $label) }`;
const REMOVE = gql`mutation DeleteMedia($id: ID!) { deleteMedia(id: $id) }`;
export function Pager({ page, total, onPage }: { page: number; total: number; onPage: (p: number) => void }) { return <div className="pagination"><button disabled={!page} onClick={() => onPage(page - 1)}>Anterior</button><span>{total} registros · Página {page + 1}</span><button disabled={(page + 1) * 30 >= total} onClick={() => onPage(page + 1)}>Siguiente</button></div>; }
function useSearch(value: string) { const [search, setSearch] = useState(value); useEffect(() => { const timer = setTimeout(() => setSearch(value), 300); return () => clearTimeout(timer); }, [value]); return search; }
const blankAccount = { name: "", email: "", password: "", role: "CUSTOMER", status: "ACTIVE" };
export function AccountsPanel({ currentUserId }: { currentUserId: string }) {
  const client = useApolloClient();
  const [search, setSearch] = usePanelFilter("q",""); const debounced = useSearch(search); const [page, setPage] = usePanelFilter("page",0);
  const [edit, setEdit] = useState<string | null | undefined>(); const [form, setForm] = useState(blankAccount); const [message, setMessage] = useState("");
  const query = useQuery<{ accounts: { rows: AuthUser[]; total: number } }>(ACCOUNTS, { variables: { filters: { search: debounced, offset: page * 30 } }, fetchPolicy: "network-only" });
  const [save, mutation] = useMutation(SAVE);
  // C69: Administración quita la verificación en dos pasos de otra cuenta (teléfono perdido).
  const [resetTwoFactor] = useMutation(RESET_TWO_FACTOR); const confirmReset = useConfirm();
  const saving=useRef(false); const [savingAccount,setSavingAccount]=useState(false);
  const leave=useLeaveGuard(); const [baseline,setBaseline]=useState(JSON.stringify(blankAccount));
  useUnsavedChanges(edit!==undefined && JSON.stringify(form)!==baseline, {busy:savingAccount || mutation.loading});
  return <section className="admin-section"><div className="section-heading"><div><span className="kicker">Sistema / Accesos</span><h1>Usuarios y cuentas</h1><p>Alta, edición de datos, cambio de contraseña y baja por bloqueo.</p></div><button className="publish" onClick={async () => { if(!await leave())return; setBaseline(JSON.stringify(blankAccount)); setEdit(null); setForm(blankAccount); setMessage(""); }}>Crear usuario</button></div>
    <div className="filter-bar"><label>Buscar nombre o correo<input value={search} onChange={(e) => { setSearch(e.target.value); setPage(0); }} /></label><button onClick={() => void query.refetch().catch(() => {})}>Actualizar</button></div>
    {query.error && <p role="alert">{query.error.message}</p>}{query.loading && <p role="status">Cargando cuentas…</p>}
    {edit === undefined && message && <p role="status">{message}</p>}
    {edit !== undefined && <form className="report-card" onSubmit={async (e) => { e.preventDefault(); if(saving.current)return; saving.current=true;setSavingAccount(true);setMessage(""); try { const { password, ...input } = form; await save({ variables: { id: edit, input: { ...input, ...(password ? { password } : {}) } } }); setEdit(undefined); setForm(blankAccount);setMessage("Cuenta guardada correctamente."); try { if (edit === currentUserId) await client.refetchQueries({ include: ["Me"] }); else await query.refetch(); } catch { setMessage("Cuenta guardada. Actualiza la lista para ver los últimos datos."); } } catch (error) { setMessage(error instanceof Error ? error.message : "Error al guardar"); } finally {saving.current=false;setSavingAccount(false);} }}><fieldset disabled={savingAccount} className="matrix-fieldset"><h2>{edit ? "Editar cuenta" : "Nueva cuenta"}</h2><div className="fields two"><label>Nombre<input required minLength={2} maxLength={80} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Correo<input required type="email" maxLength={120} value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>{edit ? "Nueva contraseña (vacía para conservar)" : "Contraseña"} <small>{form.role === "CUSTOMER" ? "mínimo 8 caracteres" : "mínimo 12 caracteres, sin contraseñas comunes ni el correo"}</small><input type="password" autoComplete="new-password" required={!edit} minLength={form.role === "CUSTOMER" ? 8 : 12} maxLength={120} title={form.role === "CUSTOMER" ? "Mínimo 8 caracteres" : "Personal del panel: mínimo 12 caracteres, sin contraseñas comunes ni el correo"} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><label>Rol<select disabled={edit === currentUserId} value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="CUSTOMER">Cliente</option><option value="CATALOG">Catálogo</option><option value="WAREHOUSE">Inventario y pedidos</option><option value="MANAGER">Gerencia (consulta)</option><option value="ADMIN">Administrador</option></select></label><label>Estado<select disabled={edit === currentUserId} value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="ACTIVE">Activo</option><option value="BLOCKED">Bloqueado (baja)</option></select></label></div><p className="method-note">Las claves se almacenan con hash y nunca se muestran. Guardar cambios revoca las sesiones anteriores de esta cuenta; si editas tu cuenta deberás iniciar sesión nuevamente.</p>{message && <p role="alert">{message}</p>}<button className="publish" disabled={mutation.loading}>Guardar cuenta</button> <button type="button" onClick={async () => { if(!await leave())return; setEdit(undefined); setForm(blankAccount); }}>Cancelar</button></fieldset></form>}
    <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Usuario</th><th>Correo</th><th>Rol</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{query.data?.accounts.rows.map((u) => <tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{roleLabels[u.role]}</td><td>{u.status}{u.twoFactorEnabled ? " · 2 pasos" : ""}</td><td>{u.twoFactorEnabled && u.id !== currentUserId && <button onClick={async () => { if (!await confirmReset({ title: "Quitar verificación en dos pasos", message: `${u.name} podrá entrar solo con su contraseña y se cerrarán sus sesiones. Hazlo solo si perdió su teléfono y ya confirmaste que es esa persona.`, confirmLabel: "Quitar", danger: true })) return; try { await resetTwoFactor({ variables: { id: u.id } }); setMessage(`Se quitó la verificación en dos pasos de ${u.name}.`); await query.refetch(); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo quitar."); } }}>Quitar 2 pasos</button>}<button onClick={async () => { if(!await leave())return; const next={ name: u.name, email: u.email, role: u.role, status: u.status, password: "" }; setBaseline(JSON.stringify(next)); setEdit(u.id); setForm(next); setMessage(""); }}>Editar / dar de baja</button></td></tr>)}</tbody></table></div>{query.data?.accounts.total === 0 && <p>No se encontraron cuentas.</p>}<Pager page={page} total={query.data?.accounts.total ?? 0} onPage={setPage} />
  </section>;
}
export { AuditPanel } from "../features/audit/AuditPanel";
function JsonDetail({ title, value }: { title: string; value: unknown }) { return <div className="json-detail"><h3>{title}</h3><pre>{JSON.stringify(value, null, 2)}</pre></div>; }
type RecordRow = Record<string, unknown> & { id: string };
function readCursors(raw:string):Array<string|undefined>{try{const values:unknown=JSON.parse(raw);return Array.isArray(values)&&values.every(value=>value===null||typeof value==="string")?values.map(value=>value??undefined):[undefined];}catch{return[undefined];}}
export function DatabasePanel({ onNavigate, onProduct, orderEditor }: { onNavigate: (section: Section) => void; onProduct: (product: Product) => void; orderEditor: (row: RecordRow | null) => ReactNode }) {
  const [entity, setEntity] = usePanelFilter("entity","products"); const [page, setPage] = usePanelFilter("page",0); const [cursorData, setCursorData] = usePanelFilter("cursors","[null]"); const cursors=readCursors(cursorData); const setCursors=(values:Array<string|undefined>)=>setCursorData(JSON.stringify(values)); const [search, setSearch] = usePanelFilter("q",""); const debounced = useSearch(search); const [selected, setSelected] = useState<RecordRow | null>(null); const [order, setOrder] = useState<RecordRow | null | undefined>();
  const query = useQuery<{ databaseRecords: { rows: RecordRow[]; total: number; pageInfo?: { endCursor: string; hasNextPage: boolean } } }>(RECORDS, { variables: { entity, filters: { offset: page * 30, after: cursors[page], search: debounced } }, fetchPolicy: "network-only" });
  const leave=useLeaveGuard();
  useEffect(()=>{setSelected(null);setOrder(undefined);},[entity]);
  useEffect(()=>{if(entity==="products"&&page>0&&!cursors[page])setPage(0);},[entity,page,cursorData]);
  const changeEntity = async (value: string) => { if(!await leave())return; setEntity(value); setPage(0); setCursors([undefined]); setSelected(null); setOrder(undefined); setSearch(""); };
  return <section className="admin-section"><div className="section-heading"><div><span className="kicker">Sistema / Base de datos</span><h1>Gestión de colecciones</h1><p>Las colecciones actuales de la aplicación, con operaciones que conservan las reglas del negocio.</p></div><button onClick={() => void query.refetch().catch(() => {})}>Actualizar</button></div><div className="filter-bar"><label>Colección<select value={entity} onChange={(e) => changeEntity(e.target.value)}>{[["products", "Productos"], ["users", "Usuarios"], ["orders", "Pedidos"], ["media", "Imágenes"], ["suppliers", "Proveedores"], ["warehouses", "Bodegas"], ["purchases", "Compras"], ["expenses", "Gastos"], ["movements", "Movimientos"], ["audit", "Auditoría"]].map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></label><label>Buscar<input value={search} onChange={(e) => { setSearch(e.target.value); setPage(0); setCursors([undefined]); }} /></label><button onClick={() => onNavigate(entity === "users" ? "customers" : entity as Section)}>Abrir módulo</button>{entity === "orders" && <button onClick={async () => { if(await leave())setOrder(null); }}>Crear pedido</button>}</div>
    <p className="method-note">Productos: crear, editar, archivar y restaurar. Usuarios: crear, editar y bloquear. Pedidos: crear, editar datos y cancelar devolviendo stock. Imágenes: subir, etiquetar y eliminar si no están vinculadas. Proveedores y bodegas: crear, editar y archivar. Compras: borrador, confirmación, recepción y cancelación. Movimientos y auditoría: consulta y exportación, sin borrado.</p>
    {query.loading && <p role="status">Cargando registros…</p>}{query.error && <p role="alert">{query.error.message}</p>}
    <div className="data-table-wrap"><table className="data-table"><thead><tr><th>ID</th><th>Registro</th><th>Estado / formato</th><th>Acciones</th></tr></thead><tbody>{query.data?.databaseRecords.rows.map((r) => <tr key={r.id}><td><small>{r.id}</small></td><td>{String(r.title ?? r.name ?? r.orderNumber ?? r.label ?? r.description ?? r.action ?? r.id)}</td><td>{String(r.status ?? r.contentType ?? (r.active === false ? "Archivado" : "Activo"))}</td><td><button onClick={() => setSelected(r)}>Ver campos</button>{entity === "products" && <button onClick={() => onProduct(r as unknown as Product)}>Editar</button>}{entity === "orders" && <button onClick={async () => { if(await leave())setOrder(r); }}>Editar datos</button>}</td></tr>)}</tbody></table></div><Pager page={page} total={query.data?.databaseRecords.total ?? 0} onPage={(p) => { if (p > page && entity === "products") setCursors([...cursors.slice(0, p), query.data?.databaseRecords.pageInfo?.endCursor]); setPage(p); }} />
    {selected && <article className="report-card"><button onClick={() => setSelected(null)}>Cerrar detalle</button><JsonDetail title="Campos almacenados" value={selected} /></article>}
    {order !== undefined && <article className="report-card"><button onClick={async () => { if(await leave())setOrder(undefined); }}>Cerrar editor de pedido</button>{orderEditor(order)}</article>}
  </section>;
}
export function MediaPanel({ onSelect, onBusyChange }: { onSelect?: (url: string) => void; onBusyChange?: (busy: boolean) => void }) {
  const confirm=useConfirm();const [search,setSearch]=usePanelFilter(onSelect?"media.q":"q","");const term=useSearch(search);
  const [page, setPage] = usePanelFilter(onSelect?"media.page":"page",0); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [labels, setLabels] = useState<Record<string, string>>({});
  const query = useQuery<{ databaseRecords: { rows: Array<{ id: string; label?: string; size: number; width?: number; height?: number }>; total: number } }>(RECORDS, { variables: { entity: "media", filters: { offset: page * 30, search: term } }, fetchPolicy: "network-only" });
  const uploads=useImageQueue(()=>{void query.refetch().catch(() => setMessage("Imagen guardada. Actualiza la biblioteca para verla."));});
  useEffect(() => { onBusyChange?.(busy || uploads.busy); }, [busy, uploads.busy, onBusyChange]);
  useUnsavedChanges(Object.keys(labels).length>0,{busy:busy||uploads.busy});
  const [rename] = useMutation(RENAME); const [remove] = useMutation(REMOVE);
  const run = async (action: () => Promise<unknown>) => { setBusy(true); setMessage(""); try { await action(); await query.refetch(); } catch (e) { setMessage(e instanceof Error ? e.message : "Error de imagen"); } finally { setBusy(false); } };
  return <section className="admin-section"><div className="section-heading"><div><span className="kicker">Administración / Fotografías</span><h1>Biblioteca de imágenes</h1><p>WebP automático, orientación corregida y lado máximo de 1400 px.</p></div><label className="upload-button">Subir imágenes<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/avif,image/gif,image/tiff" disabled={busy || uploads.busy} onChange={(e) => { const files = [...e.target.files ?? []]; e.target.value=""; uploads.add(files); }} /></label></div>
    <div className="filter-bar"><label>Buscar nombre o referencia<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} /></label></div>{uploads.view}
    {(message || query.error) && <p role="alert">{message || query.error?.message}</p>}{(busy || query.loading) && <p role="status">Procesando imágenes…</p>}<div className="media-grid">{query.data?.databaseRecords.rows.map((r) => <article className="media-card" key={r.id}><img loading="lazy" decoding="async" src={`${MEDIA_URL}/${r.id}?size=thumb`} alt={r.label || "Imagen de biblioteca"} width={240} height={180} /><small>{Math.round(r.size / 1024)} KB · {r.width ?? "?"} × {r.height ?? "?"}</small><label>Nombre<input maxLength={140} readOnly={!!onSelect} disabled={busy || uploads.busy} value={labels[r.id] ?? r.label ?? ""} onChange={(e) => setLabels(current=>{const next={...current};if(e.target.value===(r.label??""))delete next[r.id];else next[r.id]=e.target.value;return next;})} /></label><div className="row-actions">{!onSelect&&<button disabled={busy||labels[r.id]===undefined} onClick={() => void run(async () => {await rename({ variables: { id: r.id, label: labels[r.id] ?? r.label ?? "" } });setLabels(current=>{const next={...current};delete next[r.id];return next;});})}>Guardar nombre</button>}{onSelect ? <button disabled={busy || uploads.busy} onClick={() => onSelect(`${MEDIA_URL}/${r.id}`)}>Usar foto</button> : <button disabled={busy} onClick={async () => { if (await confirm({title:"Eliminar fotografía",message:"Se eliminará de la biblioteca si no está vinculada a productos ni pedidos.",danger:true,confirmLabel:"Eliminar"})) void run(async () => {await remove({ variables: { id: r.id } });setLabels(current=>{const next={...current};delete next[r.id];return next;});}); }}>Eliminar</button>}</div></article>)}</div>{query.data?.databaseRecords.total === 0 && <p>Todavía no hay imágenes subidas.</p>}<Pager page={page} total={query.data?.databaseRecords.total ?? 0} onPage={setPage} />
  </section>;
}
