import { gql, useApolloClient, useQuery } from "@apollo/client";
import { usePanelFilter } from "../../lib/usePanelRoute";
import { useEffect, useState } from "react";
import { Pager } from "../../components/SystemPanels";
import { exportCsv } from "../../components/ManagementPanel";
const AUDIT=gql`query Audit($filters:JSON){auditEvents(filters:$filters)}`;
type Row={id:string;operationId?:string;createdAt:string;actorEmail:string;actorId:string;action:string;entity:string;entityId:string;status:string;requestId:string;ip:string;before:unknown;after:unknown;input:unknown;error?:string};
const actions:Record<string,string>={saveExpense:"Guardar gasto",voidExpense:"Anular gasto",recordOrderReturn:"Registrar devolución",recordOrderRefund:"Registrar reembolso",upsertProduct:"Guardar producto",createProduct:"Crear producto",updateProduct:"Editar producto",deleteProduct:"Archivar producto",restoreProduct:"Restaurar producto",adjustStock:"Ajustar inventario",transferStock:"Trasladar mercancía",editTaxonomy:"Modificar categorías o marcas",createCheckoutOrder:"Crear pedido",updateOrderStatus:"Cambiar estado del pedido",editOrderDetails:"Editar datos de entrega",saveAccount:"Guardar cuenta",updateUserRole:"Cambiar permisos",updateUserStatus:"Cambiar acceso",login:"Iniciar sesión",logout:"Cerrar sesión",register:"Registrar cuenta",saveSupplier:"Guardar proveedor",saveWarehouse:"Guardar bodega",savePurchase:"Guardar compra",changePurchase:"Cambiar estado de compra",uploadMedia:"Subir fotografía",renameMedia:"Renombrar fotografía",deleteMedia:"Eliminar fotografía",revokeSessions:"Cerrar sesiones",requestPasswordReset:"Solicitar recuperación",resetPassword:"Restablecer contraseña",importProducts:"Importar catálogo"};
const entities:Record<string,string>={expenses:"Gastos",products:"Productos",orders:"Pedidos",users:"Cuentas",media:"Fotografías",suppliers:"Proveedores",warehouses:"Bodegas",purchases:"Compras",access:"Consultas"};
const labels:Record<string,string>={amount:"Importe",date:"Fecha del gasto",category:"Categoría",description:"Concepto",reference:"Comprobante",voidReason:"Motivo de anulación",createdByName:"Registrado por",updatedByName:"Modificado por",title:"Nombre",brand:"Marca",slug:"Identificador",shortDescription:"Descripción",stock:"Stock",reorderPoint:"Mínimo",price:"Precio",status:"Estado",active:"Activo",email:"Correo",name:"Nombre",role:"Rol",variants:"Variantes",images:"Fotografías",categories:"Categorías",goals:"Objetivos",customer:"Cliente",quantity:"Cantidad",unitCost:"Costo",notes:"Notas",items:"Líneas",lot:"Lote",expiresOn:"Vencimiento"};
function flatten(value:unknown,path="",result:Record<string,unknown>={}) { if(value && typeof value==="object") Object.entries(value).forEach(([k,v])=>{if(!["__v","updatedAt","createdAt","_id","id"].includes(k))flatten(v,path?`${path}.${k}`:k,result);});else if(path)result[path]=value;return result; }
export function changes(before:unknown,after:unknown) {const a=flatten(before),b=flatten(after);return [...new Set([...Object.keys(a),...Object.keys(b)])].filter(k=>JSON.stringify(a[k])!==JSON.stringify(b[k])).map(path=>({path,before:a[path],after:b[path]}));}
const show=(v:unknown)=>v===undefined?"—":v===null?"Vacío":v===true?"Sí":v===false?"No":String(v);
const actionLabel=(action:string)=>actions[action]??(action.startsWith("read:")?`Consultar ${action.slice(5)}`:action);
export function AuditPanel({initialSearch=""}:{initialSearch?:string}){
 const client=useApolloClient();const[search,setSearch]=usePanelFilter("q",initialSearch.startsWith("status:")?"":initialSearch);const[term,setTerm]=useState(search);const[page,setPage]=usePanelFilter("page",0);const[entity,setEntity]=usePanelFilter("entity","");const[status,setStatus]=usePanelFilter("status",initialSearch.startsWith("status:")?initialSearch.slice(7):"RESULT");const[scope,setScope]=usePanelFilter("scope","OPERATIONS");const[from,setFrom]=usePanelFilter("from","");const[to,setTo]=usePanelFilter("to","");const[selected,setSelected]=useState<Row|null>(null);const[exporting,setExporting]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{const timer=setTimeout(()=>setTerm(search),300);return()=>clearTimeout(timer);},[search]);
 useEffect(()=>{setSelected(null);},[search,status,scope,entity,from,to]);
 const dateBound=(value:string,end:boolean)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return undefined;const date=new Date(`${value}T${end?"23:59:59.999":"00:00:00"}-05:00`);return Number.isNaN(date.getTime())?undefined:date.toISOString();};
 const filters={search:term,entity,status:status==="ALL"?"":status,scope,...(dateBound(from,false)?{from:dateBound(from,false)}:{}),...(dateBound(to,true)?{to:dateBound(to,true)}:{})};
 const query=useQuery<{auditEvents:{rows:Row[];total:number}}>(AUDIT,{variables:{filters:{...filters,offset:page*30}},fetchPolicy:"network-only"});const rows=query.data?.auditEvents.rows??[];
 const exportAll=async()=>{setExporting(true);setError("");try{const until=filters.to??new Date().toISOString();const all:Row[]=[];let total=1;while(all.length<total){const r=await client.query<{auditEvents:{rows:Row[];total:number}}>({query:AUDIT,variables:{filters:{...filters,to:until,limit:100,offset:all.length}},fetchPolicy:"no-cache"});total=r.data.auditEvents.total;if(!r.data.auditEvents.rows.length)break;all.push(...r.data.auditEvents.rows);}exportCsv("auditoria-filtrada.csv",[["Fecha Ecuador","Actor","Operación","Entidad","Registro","Resultado","Solicitud","Operación ID","Error"],...all.map(r=>[new Date(r.createdAt).toLocaleString("es-EC",{timeZone:"America/Guayaquil"}),r.actorEmail||r.actorId,actionLabel(r.action),entities[r.entity]??r.entity,r.entityId,r.status,r.requestId,r.operationId,r.error])]);}catch(e){setError(e instanceof Error?e.message:"No se pudo exportar");}finally{setExporting(false);}};
 return <section className="admin-section"><div className="section-heading"><div><span className="kicker">SISTEMA / TRAZABILIDAD</span><h1>Auditoría</h1><p>Quién hizo cada cambio, cuándo y qué valores modificó.</p></div><div className="row-actions"><button onClick={()=>void query.refetch().catch(()=>{})}>Actualizar</button><button disabled={exporting||query.loading} onClick={()=>void exportAll()}>{exporting?"Exportando…":"Exportar resultados CSV"}</button></div></div><div className="filter-bar"><label>Buscar actor, operación o registro<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label><label>Tipo<select value={scope} onChange={e=>{setScope(e.target.value);setPage(0);}}><option value="OPERATIONS">Cambios y accesos de cuenta</option><option value="ACCESS">Consultas de información</option><option value="ALL">Todo</option></select></label><label>Entidad<select value={entity} onChange={e=>{setEntity(e.target.value);setPage(0);}}><option value="">Todas</option>{Object.entries(entities).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Resultado<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="RESULT">Resultados finales</option><option value="SUCCESS">Completadas</option><option value="FAILED">Fallidas</option><option value="UNRESOLVED">En curso / sin resultado</option><option value="STARTED">Todos los inicios</option><option value="ALL">Inicio y resultado</option></select></label><label>Desde<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(0);}}/></label><label>Hasta<input type="date" min={from} value={to} onChange={e=>{setTo(e.target.value);setPage(0);}}/></label><button onClick={()=>{setSearch("");setEntity("");setFrom("");setTo("");setStatus("RESULT");setScope("OPERATIONS");setPage(0);}}>Limpiar filtros</button></div>
 <p className="method-note">Horario de Ecuador. Cada operación registra un inicio y un resultado. “En curso / sin resultado” identifica automáticamente los inicios que todavía no tienen cierre. El historial empieza con la instalación de la auditoría.</p>{(query.error||error)&&<p role="alert">{query.error?.message||error}</p>}{query.loading&&<p role="status">Cargando operaciones…</p>}<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Fecha</th><th>Responsable</th><th>Operación</th><th>Entidad</th><th>Resultado</th><th>Detalle</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.createdAt).toLocaleString("es-EC",{timeZone:"America/Guayaquil"})}</td><td>{r.actorEmail||r.actorId}</td><td>{actionLabel(r.action)}</td><td>{entities[r.entity]??r.entity}<small>{r.entityId}</small></td><td><span className={`status-pill status-${r.status}`}>{r.status==="SUCCESS"?"Completada":r.status==="FAILED"?"Fallida":"Iniciada"}</span></td><td><button onClick={()=>{setSelected(r);setTimeout(()=>document.getElementById("audit-detail")?.scrollIntoView({behavior:"smooth",block:"start"}),0);}}>Ver cambios</button></td></tr>)}</tbody></table></div>{!query.loading&&!rows.length&&<p className="empty-state">No hay operaciones para estos filtros.</p>}<Pager page={page} total={query.data?.auditEvents.total??0} onPage={setPage}/>
 {selected&&<article className="report-card" id="audit-detail"><div className="section-heading"><div><h2>{actionLabel(selected.action)}</h2><p>{selected.actorEmail||selected.actorId} · {new Date(selected.createdAt).toLocaleString("es-EC",{timeZone:"America/Guayaquil"})}</p></div><button onClick={()=>setSelected(null)}>Cerrar detalle</button></div>{selected.error&&<p className="admin-alert" role="alert">{selected.error}</p>}{selected.status==="SUCCESS"&&selected.after&&typeof selected.after==="object"?<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Campo</th><th>Antes</th><th>Después</th></tr></thead><tbody>{changes(selected.before,selected.after).map(c=><tr key={c.path}><td>{c.path.split(".").map(p=>labels[p]??p).join(" / ")}</td><td>{show(c.before)}</td><td>{show(c.after)}</td></tr>)}</tbody></table></div>:<p>{selected.status==="FAILED"?"La operación no se completó. Revisa el motivo y los datos enviados.":"El detalle técnico contiene la solicitud y su resultado."}</p>}<div className="row-actions"><button onClick={()=>{setSearch(selected.operationId||selected.requestId);setScope("ALL");setStatus("ALL");setPage(0);}}>Ver inicio y resultado</button><button onClick={()=>{setSearch(selected.entityId);setScope("ALL");setStatus("RESULT");setPage(0);}}>Historial del registro</button></div><details className="technical-details"><summary>Datos técnicos y solicitud completa</summary><p>Solicitud: {selected.requestId} · Operación: {selected.operationId??"Versión anterior"} · IP: {selected.ip||"No disponible"}</p><pre>{JSON.stringify({antes:selected.before,despues:selected.after,entrada:selected.input},null,2)}</pre></details></article>}
 </section>;
}
