import { MovementTimeline } from "./MovementTimeline";
import { LotAdjustment } from "../../components/LotAdjustment";
import { useUnsavedChanges, useLeaveGuard } from "../../components/common/UnsavedChanges";
import { usePanelFilter } from "../../lib/usePanelRoute";
import { gql, useApolloClient, useMutation, useQuery } from "@apollo/client";
import { useEffect, useRef, useState } from "react";
import { GET_ADMIN_PRODUCTS, type ProductConnection } from "@vital-forge/shared-logic";
import { formatMoney } from "@vital-forge/ui-core";
import { type Section, sectionLabel } from "../../components/layout/navigation";
import { Pager } from "../../components/SystemPanels";
import { exportCsv } from "../../components/ManagementPanel";
import { useConfirm } from "../../components/common/ConfirmDialog";
const OVERVIEW=gql`query SupplyOverview { supplyOverview }`;
const MOVEMENTS=gql`query StockMovements($filters:JSON) { stockMovements(filters:$filters) }`;
const SAVE_SUPPLIER=gql`mutation SaveSupplier($id:ID,$input:JSON!){saveSupplier(id:$id,input:$input)}`;
const SAVE_WAREHOUSE=gql`mutation SaveWarehouse($id:ID,$input:JSON!){saveWarehouse(id:$id,input:$input)}`;
const SAVE_PURCHASE=gql`mutation SavePurchase($id:ID,$input:JSON!,$revision:Int){savePurchase(id:$id,input:$input,revision:$revision)}`;
const CHANGE=gql`mutation ChangePurchase($id:ID!,$status:String!,$revision:Int!){changePurchase(id:$id,status:$status,revision:$revision)}`;
const TRANSFER=gql`mutation TransferStock($input:JSON!){transferStock(input:$input)}`;
type Supplier={id:string;name:string;contact:string;email:string;phone:string;address:string;leadDays:number;active:boolean};
type Warehouse={id:string;name:string;address:string;active:boolean};
type Item={productId:string;sku:string;title:string;quantity:number;unitCost:number;lot:string;expiresOn:string};
type Purchase={id:string;number:string;supplierId:string;warehouseId:string;expectedOn:string;notes:string;items:Item[];status:string;total:number;revision:number};
type Position={productId:string;sku:string;title:string;warehouseId:string;lot:string;expiresOn:string;quantity:number;reserved:number;available:number;onHand:number;unitCost:number|null};
type Movement=Position&{actorName?:string;id:string;delta:number;before:number;after:number;createdAt:string;reason:string;actorId:string;requestId:string};
type Overview={suppliers:Supplier[];warehouses:Warehouse[];purchases:Purchase[];positions:Position[]};
const blankSupplier={name:"",contact:"",email:"",phone:"",address:"",leadDays:7,active:true};
const blankWarehouse={name:"",address:"",active:true};
const statusLabel:Record<string,string>={DRAFT:"Borrador",ORDERED:"En camino",RECEIVED:"Recibida",CANCELLED:"Cancelada"};
export function SupplyPanel({section,readonly=false,initialSearch=""}:{section:Section;readonly?:boolean;initialSearch?:string}) {
 const client=useApolloClient(); const confirm=useConfirm(); const [search,setSearch]=usePanelFilter("q",initialSearch.startsWith("status:")?"":initialSearch); const [term,setTerm]=useState(initialSearch.startsWith("status:")?"":initialSearch);const [page,setPage]=usePanelFilter("page",0);const [status,setStatus]=usePanelFilter("status",initialSearch.startsWith("status:")?initialSearch.slice(7):"");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const [supplier,setSupplier]=useState<(typeof blankSupplier&{id?:string})|null>(null);const [warehouse,setWarehouse]=useState<(typeof blankWarehouse&{id?:string})|null>(null);const [purchase,setPurchase]=useState<Purchase|null>(null);const [transfer,setTransfer]=useState<(Position&{to:string;amount:number;reason:string})|null>(null);
 useEffect(()=>{const timer=setTimeout(()=>setTerm(search),300);return()=>clearTimeout(timer);},[search]);
 const query=useQuery<{supplyOverview:Overview}>(OVERVIEW,{fetchPolicy:"network-only"});
 const movements=useQuery<{stockMovements:{rows:Movement[];total:number}}>(MOVEMENTS,{variables:{filters:{search:term,offset:page*30}},skip:section!=="movements",fetchPolicy:"network-only"});
 const [saveSupplier]=useMutation(SAVE_SUPPLIER);const [saveWarehouse]=useMutation(SAVE_WAREHOUSE);const [savePurchase]=useMutation(SAVE_PURCHASE);const [change]=useMutation(CHANGE);const [move]=useMutation(TRANSFER);
 const [lotAdjustment,setLotAdjustment]=useState<Position|null>(null);
 const leave=useLeaveGuard(); const operationRef=useRef(false); const [purchaseVersion,setPurchaseVersion]=useState(0); const [supplierBase,setSupplierBase]=useState(""); const [warehouseBase,setWarehouseBase]=useState("");
 useUnsavedChanges(Boolean(supplier&&JSON.stringify(supplier)!==supplierBase||warehouse&&JSON.stringify(warehouse)!==warehouseBase||transfer&&(transfer.to||transfer.reason||transfer.amount!==1)),{busy});
 const closeEditors=()=>{setSupplier(null);setWarehouse(null);setPurchase(null);setTransfer(null);setLotAdjustment(null);};
 const openSupplier=async(value:typeof supplier)=>{if(await leave()){closeEditors();setSupplierBase(JSON.stringify(value));setSupplier(value);}};
 const openWarehouse=async(value:typeof warehouse)=>{if(await leave()){closeEditors();setWarehouseBase(JSON.stringify(value));setWarehouse(value);}};
 const openPurchase=async(value:typeof purchase)=>{if(await leave()){closeEditors();setPurchaseVersion(version=>version+1);setPurchase(value);}};
 const openTransfer=async(value:typeof transfer)=>{if(await leave()){closeEditors();setTransfer(value);}};
 const data=query.data?.supplyOverview;const name=(id:string,kind:"suppliers"|"warehouses")=>data?.[kind].find(r=>r.id===id)?.name??id;
 const run=async(work:()=>Promise<unknown>,success:string)=>{if(operationRef.current)return;operationRef.current=true;setBusy(true);setMessage("");try{await work();setMessage(success);await client.refetchQueries({include:"active"}).catch(()=>setMessage(`${success} Actualiza para ver los últimos datos.`));}catch(e){setMessage(e instanceof Error?e.message:"No se pudo guardar");}finally{operationRef.current=false;setBusy(false);}};
 const match=(value:string)=>value.toLocaleLowerCase().includes(term.toLocaleLowerCase());
 const suppliers=(data?.suppliers??[]).filter(s=>match(`${s.name} ${s.email} ${s.phone}`));const warehouses=(data?.warehouses??[]).filter(w=>match(`${w.name} ${w.address}`));const positions=(data?.positions??[]).filter(p=>p.onHand>0&&match(`${p.title} ${p.sku} ${p.lot} ${name(p.warehouseId,"warehouses")}`));const purchases=(data?.purchases??[]).filter(p=>(!status||p.status===status)&&match(`${p.number} ${name(p.supplierId,"suppliers")} ${p.items.map(i=>i.sku).join(" ")}`));
 const transition=async(p:Purchase,next:string)=>{if(!await leave())return;if(await confirm({title:next==="RECEIVED"?`Recibir ${p.number}`:next==="ORDERED"?"Confirmar compra":"Cancelar compra",message:next==="RECEIVED"?`Se sumarán ${p.items.reduce((s,i)=>s+i.quantity,0)} unidades a ${name(p.warehouseId,"warehouses")}, conservando lotes, vencimientos y costos. Confirma cuando hayas recibido toda la mercancía.`:next==="ORDERED"?"La compra aparecerá en tránsito y se tendrá en cuenta para la reposición.":"La compra quedará cancelada y no modificará el inventario.",confirmLabel:next==="RECEIVED"?"Confirmar recepción":"Confirmar",danger:next==="CANCELLED"}))await run(async()=>{await change({variables:{id:p.id,status:next,revision:p.revision}});closeEditors();},"Compra actualizada.");};
 return <section className="admin-section"><div className="section-heading"><div><span className="kicker">INVENTARIO Y COMPRAS</span><h1>{sectionLabel(section)}</h1><p>{section==="purchases"?"Prepara la compra, confirma el envío y recibe la mercancía una sola vez.":section==="warehouses"?"Ubicación, lotes, vencimientos y traslado de mercancía.":section==="suppliers"?"Contactos y plazos de entrega para organizar tus compras.":"Cada entrada, salida y traslado conserva su motivo y responsable."}</p></div><div className="row-actions"><button disabled={busy} onClick={()=>void run(()=>query.refetch(),"Datos actualizados.")}>Actualizar</button>{!readonly&&section==="suppliers"&&<button className="primary-button" onClick={()=>void openSupplier(blankSupplier)}>Nuevo proveedor</button>}{!readonly&&section==="warehouses"&&<button className="primary-button" onClick={()=>void openWarehouse(blankWarehouse)}>Nueva bodega</button>}{!readonly&&section==="purchases"&&<button className="primary-button" onClick={()=>void openPurchase({id:"",number:"Nueva compra",supplierId:"",warehouseId:"main",expectedOn:"",notes:"",items:[],status:"DRAFT",total:0,revision:0})}>Nueva compra</button>}</div></div>
 {(message||query.error||movements.error)&&<p className="admin-alert" role="status">{message||query.error?.message||movements.error?.message}</p>}{query.loading&&<p role="status">Cargando inventario…</p>}
 <div className="filter-bar"><label>Buscar<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder={section==="movements"?"Producto, SKU o motivo":"Nombre, SKU o referencia"}/></label>{section==="purchases"&&<label>Estado<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">Todos</option>{Object.entries(statusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}</div>
 {supplier&&<form className="report-card" onSubmit={e=>{e.preventDefault();void run(async()=>{const{id,...input}=supplier;await saveSupplier({variables:{id,input}});setSupplier(null);},"Proveedor guardado.");}}><h2>{supplier.id?"Editar proveedor":"Nuevo proveedor"}</h2><fieldset disabled={busy} style={{border:0,padding:0,margin:0,minWidth:0}}><div className="fields two">{([['name','Nombre'],['contact','Contacto'],['email','Correo'],['phone','Teléfono'],['address','Dirección']] as const).map(([key,label])=><label key={key}>{label}<input required={key==="name"} type={key==="email"?"email":"text"} minLength={key==="name"?2:undefined} maxLength={key==="address"?240:key==="phone"?30:120} value={supplier[key]} onChange={e=>setSupplier({...supplier,[key]:e.target.value})}/></label>)}<label>Plazo de entrega (días)<input required type="number" min={0} max={365} value={supplier.leadDays} onChange={e=>setSupplier({...supplier,leadDays:Number(e.target.value)})}/></label></div><label className="checkbox-label"><input type="checkbox" checked={supplier.active} onChange={e=>setSupplier({...supplier,active:e.target.checked})}/>Proveedor activo</label><div className="dialog-actions"><button type="button" onClick={()=>void openSupplier(null)}>Cancelar</button><button className="primary-button" disabled={busy}>Guardar proveedor</button></div></fieldset></form>}
 {warehouse&&<form className="report-card" onSubmit={e=>{e.preventDefault();void run(async()=>{const{id,...input}=warehouse;await saveWarehouse({variables:{id,input}});setWarehouse(null);},"Bodega guardada.");}}><h2>{warehouse.id?"Editar bodega":"Nueva bodega"}</h2><fieldset disabled={busy} style={{border:0,padding:0,margin:0,minWidth:0}}><div className="fields two"><label>Nombre<input required minLength={2} maxLength={120} value={warehouse.name} onChange={e=>setWarehouse({...warehouse,name:e.target.value})}/></label><label>Dirección<input maxLength={240} value={warehouse.address} onChange={e=>setWarehouse({...warehouse,address:e.target.value})}/></label></div><label className="checkbox-label"><input disabled={warehouse.id==="main"} type="checkbox" checked={warehouse.active} onChange={e=>setWarehouse({...warehouse,active:e.target.checked})}/>Bodega activa</label><div className="dialog-actions"><button type="button" onClick={()=>void openWarehouse(null)}>Cancelar</button><button className="primary-button" disabled={busy}>Guardar bodega</button></div></fieldset></form>}
 {purchase&&data&&<PurchaseEditor key={`${purchase.id}:${purchaseVersion}`} purchase={purchase} data={data} readonly={readonly||purchase.status!=="DRAFT"} busy={busy} onCancel={()=>void openPurchase(null)} onSave={p=>void run(async()=>{const{supplierId,warehouseId,expectedOn,notes}=p;await savePurchase({variables:{id:p.id||undefined,revision:p.revision,input:{supplierId,warehouseId,expectedOn,notes,items:p.items.map(({title,...item})=>item)}}});setPurchase(null);},"Borrador de compra guardado.")}/>}
 {section==="suppliers"&&<><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Proveedor</th><th>Contacto</th><th>Plazo</th><th>Estado</th>{!readonly&&<th>Acción</th>}</tr></thead><tbody>{suppliers.slice(page*30,(page+1)*30).map(s=><tr key={s.id}><td><b>{s.name}</b><small>{s.address}</small></td><td>{s.contact}<small>{s.email} · {s.phone}</small></td><td>{s.leadDays} días</td><td>{s.active?"Activo":"Archivado"}</td>{!readonly&&<td><button onClick={()=>{const{id,name,contact,email,phone,address,leadDays,active}=s;void openSupplier({id,name,contact,email,phone,address,leadDays,active});}}>Editar / archivar</button></td>}</tr>)}</tbody></table></div>{!suppliers.length&&<p className="empty-state">No hay proveedores para estos filtros.</p>}<Pager page={page} total={suppliers.length} onPage={setPage}/></>}
 {section==="purchases"&&<><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Compra / proveedor</th><th>Destino</th><th>Esperada</th><th>Total</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{purchases.slice(page*30,(page+1)*30).map(p=><tr key={p.id}><td><b>{p.number}</b><small>{name(p.supplierId,"suppliers")}</small></td><td>{name(p.warehouseId,"warehouses")}</td><td>{p.expectedOn||"Sin fecha"}</td><td>{formatMoney(p.total)}</td><td><span className={`status-pill status-${p.status}`}>{statusLabel[p.status]}</span></td><td><div className="row-actions"><button onClick={()=>void openPurchase(p)}>{p.status==="DRAFT"&&!readonly?"Editar":"Ver detalle"}</button>{!readonly&&p.status==="DRAFT"&&<button disabled={busy} onClick={()=>void transition(p,"ORDERED")}>Confirmar compra</button>}{!readonly&&p.status==="ORDERED"&&<button disabled={busy} onClick={()=>void transition(p,"RECEIVED")}>Recibir</button>}{!readonly&&["DRAFT","ORDERED"].includes(p.status)&&<button disabled={busy} onClick={()=>void transition(p,"CANCELLED")}>Cancelar</button>}</div></td></tr>)}</tbody></table></div>{!purchases.length&&<p className="empty-state">No hay compras para estos filtros. Crea primero un proveedor y prepara una compra.</p>}<Pager page={page} total={purchases.length} onPage={setPage}/></>}
 {section==="warehouses"&&<><div className="summary-grid">{warehouses.map(w=><article className="report-card" key={w.id}><h2>{w.name}</h2><p>{w.address||"Sin dirección"} · {w.active?"Activa":"Archivada"}</p><b>{data?.positions.filter(p=>p.warehouseId===w.id).reduce((s,p)=>s+p.onHand,0)} unidades físicas</b><small>{data?.positions.filter(p=>p.warehouseId===w.id).reduce((s,p)=>s+p.reserved,0)} reservadas · {data?.positions.filter(p=>p.warehouseId===w.id).reduce((s,p)=>s+p.available,0)} disponibles</small>{!readonly&&<button onClick={()=>void openWarehouse({id:w.id,name:w.name,address:w.address,active:w.active})}>Editar / archivar</button>}</article>)}</div><article className="report-card"><div className="section-heading"><div><h2>Existencias por lote</h2><p>Las ventas reservan primero los lotes que vencen antes. Los vencidos no se reservan.</p></div><button onClick={()=>exportCsv("lotes.csv",[["Producto","SKU","Bodega","Lote","Vencimiento","Físicas","Reservadas","Disponibles","Costo unitario"],...positions.map(p=>[p.title,p.sku,name(p.warehouseId,"warehouses"),p.lot,p.expiresOn,p.onHand,p.reserved,p.available,p.unitCost])])}>Exportar CSV</button></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Producto</th><th>Bodega / lote</th><th>Vencimiento</th><th>Físicas</th><th>Reservadas</th><th>Disponibles</th><th>Costo</th>{!readonly&&<th>Acción</th>}</tr></thead><tbody>{positions.slice(page*30,(page+1)*30).map((p,i)=><tr key={i}><td>{p.title}<small>{p.sku}</small></td><td>{name(p.warehouseId,"warehouses")}<small>{p.lot}</small></td><td><span className={p.expiresOn&&p.expiresOn<=new Date(Date.now()+30*86400000).toISOString().slice(0,10)?"stock-warning":""}>{p.expiresOn||"Sin registrar"}</span></td><td>{p.onHand}</td><td>{p.reserved}</td><td>{p.available}</td><td>{p.unitCost===null?"Sin registrar":formatMoney(p.unitCost)}</td>{!readonly&&<td><button onClick={async()=>{if(await leave()){closeEditors();setLotAdjustment(p);}}}>Ajustar lote</button><button disabled={!p.available} onClick={()=>void openTransfer({...p,to:"",amount:1,reason:""})}>Trasladar</button></td>}</tr>)}</tbody></table></div>{!positions.length&&<p>No hay lotes con existencias.</p>}<Pager page={page} total={positions.length} onPage={setPage}/></article></>}
 {lotAdjustment&&<LotAdjustment key={JSON.stringify([lotAdjustment.productId,lotAdjustment.sku,lotAdjustment.warehouseId,lotAdjustment.lot,lotAdjustment.expiresOn,lotAdjustment.unitCost])} position={lotAdjustment} onSaved={message=>{setLotAdjustment(null);setMessage(message);}} onClose={async()=>{if(await leave())setLotAdjustment(null);}}/>}
 {transfer&&<form className="report-card" onSubmit={e=>{e.preventDefault();void run(async()=>{await move({variables:{input:{productId:transfer.productId,sku:transfer.sku,from:transfer.warehouseId,to:transfer.to,lot:transfer.lot,expiresOn:transfer.expiresOn,unitCost:transfer.unitCost,quantity:transfer.amount,expectedQuantity:transfer.quantity,reason:transfer.reason}}});setTransfer(null);},"Traslado registrado.");}}><h2>Trasladar {transfer.sku} · {transfer.lot}</h2><fieldset disabled={busy} style={{border:0,padding:0,margin:0,minWidth:0}}><p>Desde {name(transfer.warehouseId,"warehouses")} · {transfer.available} disponibles · {transfer.reserved} reservadas. Vencimiento: {transfer.expiresOn||"sin registrar"} · Costo unitario: {transfer.unitCost===null?"sin registrar":formatMoney(transfer.unitCost)}.</p><div className="fields two"><label>Bodega destino<select required value={transfer.to} onChange={e=>setTransfer({...transfer,to:e.target.value})}><option value="">Seleccionar</option>{data?.warehouses.filter(w=>w.active&&w.id!==transfer.warehouseId).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>Unidades<input required type="number" min={1} max={transfer.available} value={transfer.amount} onChange={e=>setTransfer({...transfer,amount:Number(e.target.value)})}/></label><label className="full">Motivo<input required minLength={5} maxLength={300} value={transfer.reason} onChange={e=>setTransfer({...transfer,reason:e.target.value})}/></label></div><div className="dialog-actions"><button type="button" onClick={()=>void openTransfer(null)}>Cancelar</button><button disabled={busy} className="primary-button">Confirmar traslado</button></div></fieldset></form>}
 {section==="movements"&&<><MovementTimeline rows={movements.data?.stockMovements.rows??[]} warehouseName={id=>name(id,"warehouses")}/><details className="biz-method"><summary>Ver tabla de movimientos</summary><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Fecha / producto</th><th>Movimiento</th><th>Stock total SKU</th><th>Bodega / lote</th><th>Motivo / responsable</th></tr></thead><tbody>{movements.data?.stockMovements.rows.map(m=><tr key={m.id}><td>{new Date(m.createdAt).toLocaleString("es-EC",{timeZone:"America/Guayaquil"})}<small>{m.title} · {m.sku}</small></td><td className={m.delta<0?"stock-warning":""}>{m.delta>0?"+":""}{m.delta}</td><td>{m.before} → {m.after}</td><td>{name(m.warehouseId,"warehouses")}<small>{m.lot}</small></td><td>{m.reason}<small>{m.actorName??m.actorId}</small><details><summary>Referencia de trazabilidad</summary>{m.requestId}</details></td></tr>)}</tbody></table></div></details>{movements.data?.stockMovements.total===0&&<p className="empty-state">Todavía no hay movimientos para estos filtros.</p>}<Pager page={page} total={movements.data?.stockMovements.total??0} onPage={setPage}/><button onClick={()=>exportCsv("movimientos-pagina.csv",[["Fecha","SKU","Variación","Antes","Después","Bodega","Lote","Motivo","Actor","Solicitud"],...(movements.data?.stockMovements.rows??[]).map(m=>[m.createdAt,m.sku,m.delta,m.before,m.after,m.warehouseId,m.lot,m.reason,m.actorId,m.requestId])])}>Exportar página CSV</button></>}
 </section>;
}
function PurchaseEditor({purchase,data,readonly,busy,onCancel,onSave}:{purchase:Purchase;data:Overview;readonly:boolean;busy:boolean;onCancel:()=>void;onSave:(p:Purchase)=>void}) {
 const [form,setForm]=useState(purchase);
 useUnsavedChanges(!readonly&&JSON.stringify(form)!==JSON.stringify(purchase),{busy});const [search,setSearch]=useState("");const [term,setTerm]=useState("");useEffect(()=>{const t=setTimeout(()=>setTerm(search),300);return()=>clearTimeout(t);},[search]);
 const products=useQuery<{searchProducts:ProductConnection}>(GET_ADMIN_PRODUCTS,{variables:{filters:{search:term,status:"ACTIVE"},pagination:{first:10}},skip:readonly});
 const item=(index:number,patch:Partial<Item>)=>setForm({...form,items:form.items.map((v,i)=>i===index?{...v,...patch}:v)});
 return <form className="report-card purchase-editor" onSubmit={e=>{e.preventDefault();onSave(form);}}><div className="section-heading"><h2>{form.number}</h2><button type="button" onClick={onCancel}>Cerrar</button></div><fieldset disabled={readonly||busy}><div className="fields two"><label>Proveedor<select required value={form.supplierId} onChange={e=>setForm({...form,supplierId:e.target.value})}><option value="">Selecciona un proveedor</option>{data.suppliers.filter(s=>s.active||s.id===form.supplierId).map(s=><option key={s.id} value={s.id}>{s.name} · {s.leadDays} días</option>)}</select></label><label>Bodega destino<select required value={form.warehouseId} onChange={e=>setForm({...form,warehouseId:e.target.value})}>{data.warehouses.filter(w=>w.active||w.id===form.warehouseId).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>Fecha esperada<input type="date" value={form.expectedOn} onChange={e=>setForm({...form,expectedOn:e.target.value})}/></label><label>Notas<input maxLength={500} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>
 {!readonly&&<><label>Agregar productos<input placeholder="Busca nombre o SKU" value={search} onChange={e=>setSearch(e.target.value)}/></label>{products.error&&<p role="alert">{products.error.message}</p>}<div className="product-picker">{products.data?.searchProducts.edges.flatMap(({node:p})=>p.variants.map(v=><button type="button" key={`${p.id}:${v.sku}`} onClick={()=>setForm({...form,items:[...form.items,{productId:p.id,sku:v.sku,title:p.title,quantity:1,unitCost:0,lot:"",expiresOn:""}]})}>+ {p.title}<small>{v.sku}</small></button>))}</div></>}
 <div className="purchase-items">{form.items.map((v,i)=><article className="purchase-item" key={i}><b>{v.title}<small>{v.sku}</small></b><div className="fields three"><label>Cantidad<input type="number" required min={1} max={100000} value={v.quantity} onChange={e=>item(i,{quantity:Number(e.target.value)})}/></label><label>Costo unitario<input type="number" step="0.01" required min="0.01" max={1000000} value={v.unitCost} onChange={e=>item(i,{unitCost:Number(e.target.value)})}/></label><label>Lote<input required maxLength={80} value={v.lot} onChange={e=>item(i,{lot:e.target.value})}/></label><label>Vencimiento<input type="date" value={v.expiresOn} onChange={e=>item(i,{expiresOn:e.target.value})}/></label><span>Subtotal: {formatMoney(v.quantity*v.unitCost)}</span>{!readonly&&<button type="button" onClick={()=>setForm({...form,items:form.items.filter((_,j)=>j!==i)})}>Quitar línea</button>}</div></article>)}</div><p>Los suplementos requieren fecha de vencimiento. La recepción es completa; registra entregas separadas en compras distintas.</p><strong>Total: {formatMoney(form.items.reduce((s,i)=>s+i.quantity*i.unitCost,0))}</strong>{!readonly&&<div className="dialog-actions"><button type="button" onClick={onCancel}>Cancelar</button><button className="primary-button" disabled={!form.items.length||busy}>Guardar borrador</button></div>}</fieldset></form>;
}
