import { describe, expect, it, vi } from "vitest";
import { demoProducts } from "../data/demoProducts.js";
import { productService } from "./product.service.js";
import { supplyService } from "./supply.service.js";
import { orderService } from "./order.service.js";
import { mailService } from "./mail.service.js";
import { telegramService } from "./telegram.service.js";
import { listMovements } from "./stockLedger.service.js";
import { unitOfWork } from "../lib/unitOfWork.js";
vi.spyOn(mailService,"sendOrderConfirmation").mockResolvedValue(true);
vi.spyOn(mailService,"sendOperatorAlert").mockResolvedValue(true);
vi.spyOn(mailService,"sendStatusUpdate").mockResolvedValue(true);
vi.spyOn(telegramService,"sendOrderAlert").mockResolvedValue(true);
let serial=0;
async function setup(stock=0){const payload=structuredClone(demoProducts[1]!);payload.slug=`supply-${++serial}`;payload.variants[0]!.stock=stock;const product=await productService.upsert(undefined,payload) as {id:string};const sku=payload.variants[0]!.sku;const supplier=await supplyService.saveSupplier(undefined,{name:`Proveedor ${serial}`,leadDays:4});return{productId:product.id,sku,supplierId:supplier.id,payload};}
const customer={fullName:"Compra de prueba",email:"test@example.com",phone:"0999999999",province:"Pichincha",city:"Quito",address:"Dirección de prueba 123",idNumber:"1700000001",reference:""};
async function purchase(f:Awaited<ReturnType<typeof setup>>,quantity=5,lot="LOTE-A",expiresOn="2090-01-01") {return supplyService.savePurchase(undefined,{supplierId:f.supplierId,warehouseId:"main",items:[{productId:f.productId,sku:f.sku,quantity,unitCost:12,lot,expiresOn}]});}
const stock=async(id:string)=>(await productService.get(id))!.variants[0]!.stock;
describe("Compras, lotes y transacciones",()=>{
 it("recibe una compra una sola vez, también con dos confirmaciones simultáneas",async()=>{const f=await setup();const draft=await purchase(f);const ordered=await supplyService.changePurchase(draft.id,"ORDERED",draft.revision);await Promise.all([supplyService.changePurchase(ordered.id,"RECEIVED",ordered.revision),supplyService.changePurchase(ordered.id,"RECEIVED",ordered.revision)]);expect(await stock(f.productId)).toBe(5);const rows=(await listMovements({productId:f.productId})).rows;expect(rows.filter(r=>r.reason?.startsWith("Recepción"))).toHaveLength(1);expect(rows.find(r=>r.reason?.startsWith("Recepción"))).toMatchObject({delta:5,unitCost:12,lot:"LOTE-A",before:0,after:5});await expect(supplyService.changePurchase(draft.id,"CANCELLED",2)).rejects.toThrow();});
 it("revierte todas las líneas y su historial si falla la recepción",async()=>{const f=await setup();const draft=await purchase(f);const ordered=await supplyService.changePurchase(draft.id,"ORDERED",0);const original=productService.changeStock.bind(productService);const spy=vi.spyOn(productService,"changeStock").mockImplementationOnce(async(...args)=>{await original(...args);throw new Error("fallo simulado al guardar");});await expect(supplyService.changePurchase(ordered.id,"RECEIVED",1)).rejects.toThrow("fallo simulado");spy.mockRestore();expect(await stock(f.productId)).toBe(0);expect((await supplyService.purchases()).find(p=>p.id===draft.id)?.status).toBe("ORDERED");expect((await listMovements({productId:f.productId})).rows.filter(m=>m.delta!==0)).toHaveLength(0);});
 it("reserva por vencimiento y devuelve las unidades a sus lotes originales al cancelar",async()=>{const f=await setup();for(const [lot,date] of [["TARDIO","2090-06-01"],["TEMPRANO","2090-01-01"]]){const draft=await purchase(f,3,lot,date);const ordered=await supplyService.changePurchase(draft.id,"ORDERED",0);await supplyService.changePurchase(ordered.id,"RECEIVED",1);}const order=await orderService.create({customer,items:[{productId:f.productId,variantSku:f.sku,quantity:4}],shippingMethod:"EXPRESS_QUITO_VALLES",paymentMethod:"BANK_TRANSFER"});const id=String("id" in order?order.id:"");const stored=await orderService.get(id);expect(stored?.items[0]?.allocations?.map(l=>[l.lot,l.quantity])).toEqual([["TEMPRANO",3],["TARDIO",1]]);expect(stored?.items[0]?.unitCost).toBe(12);await Promise.all([orderService.updateStatus(id,"CANCELLED"),orderService.updateStatus(id,"CANCELLED")]);expect(await stock(f.productId)).toBe(6);const positions=(await supplyService.positions()).filter(p=>p.productId===f.productId);expect(positions.map(p=>p.quantity)).toEqual([3,3]);});
 it("traslada sin alterar el total y protege bodegas con stock",async()=>{const f=await setup();const p=await purchase(f);await supplyService.changePurchase(p.id,"ORDERED",0);await supplyService.changePurchase(p.id,"RECEIVED",1);const target=await supplyService.saveWarehouse(undefined,{name:"Bodega secundaria"});await unitOfWork(()=>supplyService.transfer({productId:f.productId,sku:f.sku,from:"main",to:target.id,lot:"LOTE-A",quantity:2,reason:"Reubicación de prueba"}),{actorId:"warehouse-actor",requestId:"trace-transfer"});expect(await stock(f.productId)).toBe(5);expect((await supplyService.positions()).find(p=>p.productId===f.productId&&p.warehouseId===target.id)).toMatchObject({quantity:2,unitCost:12,expiresOn:"2090-01-01"});await expect(supplyService.saveWarehouse(target.id,{name:target.name,active:false})).rejects.toThrow(/stock/);expect((await listMovements({productId:f.productId})).rows.filter(m=>m.requestId==="trace-transfer")).toHaveLength(2);});
 it("dos pedidos no venden la última unidad dos veces y un pedido multilínea fallido no pierde stock",async()=>{const f=await setup(1);const input={customer,items:[{productId:f.productId,variantSku:f.sku,quantity:1}],shippingMethod:"EXPRESS_QUITO_VALLES",paymentMethod:"BANK_TRANSFER"};const results=await Promise.allSettled([orderService.create(input),orderService.create(input)]);expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect(await stock(f.productId)).toBe(0);const other=await setup(2);const before=(await listMovements({productId:other.productId})).total;await expect(productService.reserveStock([{productId:other.productId,variantSku:other.sku,quantity:1},{productId:f.productId,variantSku:f.sku,quantity:1}])).rejects.toThrow();expect(await stock(other.productId)).toBe(2);expect((await listMovements({productId:other.productId})).total).toBe(before);});
 it("rechaza lotes vencidos, suplementos sin vencimiento y revisiones antiguas",async()=>{const f=await setup();await expect(purchase(f,1,"VENCIDO","2020-01-01")).rejects.toThrow(/vencido/);await expect(purchase(f,1,"SIN-FECHA","")).rejects.toThrow(/vencimiento/);const p=await purchase(f);await supplyService.changePurchase(p.id,"ORDERED",0);await expect(supplyService.savePurchase(p.id,{supplierId:p.supplierId,warehouseId:p.warehouseId,items:p.items.map(({title,...i})=>i)},0)).rejects.toThrow(/borrador/);await expect(supplyService.saveSupplier(f.supplierId,{name:"Proveedor",active:false})).rejects.toThrow(/pendientes/);});
 it("excluye vencidos de las reservas y permite darles salida por merma",async()=>{const f=await setup();await productService.changeStock(f.productId,f.sku,2,{warehouseId:"main",lot:"ANTIGUO",expiresOn:"2020-01-01",reason:"Saldo histórico de prueba"});await expect(productService.reserveStock([{productId:f.productId,variantSku:f.sku,quantity:1}])).rejects.toThrow(/vencido/);await productService.adjustStock({productId:f.productId,sku:f.sku,expectedStock:2,delta:-2,reorderPoint:5,reason:"Baja por vencimiento"});expect(await stock(f.productId)).toBe(0);expect((await listMovements({productId:f.productId})).rows[0]).toMatchObject({delta:-2,lot:"ANTIGUO",reason:"Baja por vencimiento"});});
 it("no elimina variantes con unidades y revierte importaciones completas ante un conflicto",async()=>{const f=await setup(3);const replacement={...f.payload,variants:[{...f.payload.variants[0]!,sku:"REPLACEMENT"}]};await expect(productService.upsert(f.productId,replacement)).rejects.toThrow(/SKU/);const first={...f.payload,slug:"import-rollback"};await expect(unitOfWork(async()=>{await productService.upsert(undefined,first);await productService.upsert(undefined,f.payload);})).rejects.toThrow(/identificador/);expect(await productService.slugExists(first.slug)).toBe(false);});
});
