import { gql, useQuery } from "@apollo/client";
import { useState } from "react";
import { ArrowDownRight, ArrowRight, ArrowUpRight, ChartNoAxesCombined, CircleDollarSign, Download, Package, ReceiptText, RefreshCw, ShoppingBag, Truck, TriangleAlert } from "lucide-react";
import { formatMoney } from "@vital-forge/ui-core";
import { usePanelFilter } from "../../lib/usePanelRoute";
import type { Section } from "../../components/layout/navigation";
import { exportCsv } from "../../components/ManagementPanel";
import { HorizontalBar, StockRing, TrendChart } from "./Charts";
import { expenseLabels, localToday, monthNames, type BusinessData, type OperationsData } from "./types";

const REPORT = gql`query BusinessReport($filters: JSON!) { managementDashboard(filters: $filters) }`;
const OPERATIONS = gql`query CommercialOverview { commercialOverview }`;
const TAXONOMY = gql`query BusinessCategories { taxonomy { categories { key name } } }`;
const orderLabels: Record<string, string> = { PENDING_PAYMENT: "Esperando pago", PAYMENT_REVIEW: "Pago por confirmar", PAID: "Pagado", PREPARING: "En preparación", SHIPPED: "Enviado" };
type Props = { compact?: boolean; readonly?: boolean; onNavigate: (section: Section, search?: string) => void };

export function BusinessDashboard({ compact = false, readonly = false, onNavigate }: Props) {
  const now = localToday();
  const [rawYear, setYear] = usePanelFilter("year", Number(now.slice(0, 4)));
  const [rawMonth, setMonth] = usePanelFilter("month", Number(now.slice(5, 7)));
  const [category, setCategory] = usePanelFilter("category", "");
  const [basis, setBasis] = usePanelFilter("basis", "CREATED");
  const [message, setMessage] = useState("");
  const year = Math.max(2021, Math.min(2100, Math.trunc(rawYear)));
  const month = Math.max(0, Math.min(12, Math.trunc(rawMonth)));
  const dateBasis = basis === "PAID" ? "PAID" : "CREATED";
  const report = useQuery<{ managementDashboard: BusinessData }>(REPORT, { variables: { filters: { year, month, category: compact ? "" : category, dateBasis, coverageDays: 30 } }, fetchPolicy: "cache-and-network", notifyOnNetworkStatusChange: true });
  const operations = useQuery<{ commercialOverview: OperationsData }>(OPERATIONS, { fetchPolicy: "cache-and-network", notifyOnNetworkStatusChange: true });
  const taxonomy = useQuery<{ taxonomy: { categories: Array<{ key: string; name: string }> } }>(TAXONOMY, { skip: compact });
  const data = report.data?.managementDashboard, live = operations.data?.commercialOverview;
  const label = `${month ? monthNames[month - 1] : "Todo el año"} ${year}`;
  const comparison = month ? data?.comparison.previousMonth : data?.comparison.previousYear;
  const refresh = async () => { setMessage(""); const results = await Promise.allSettled([report.refetch(), operations.refetch()]); if (results.some(r => r.status === "rejected")) setMessage("No se pudo actualizar todo el resumen. Vuelve a intentarlo."); };
  const setPeriod = (previous = false, annual = false) => { const date = new Date(`${now}T12:00:00Z`); if (previous) date.setUTCMonth(date.getUTCMonth() - 1, 1); setYear(date.getUTCFullYear()); setMonth(annual ? 0 : date.getUTCMonth() + 1); };
  const pending = live?.orders.filter(o => ["PENDING_PAYMENT", "PAYMENT_REVIEW"].includes(o.status)).reduce((s, o) => s + o.amount, 0);
  return <section className={`business-dashboard ${compact ? "biz-compact" : "admin-section"}`} aria-label="Resumen comercial">
    <div className="biz-header"><div><span className="kicker">{compact ? "EL NEGOCIO EN UN VISTAZO" : "GERENCIA · TU NEGOCIO EN CIFRAS"}</span>{compact ? <h2>Cómo va tu negocio</h2> : <h1>Ventas y resultados</h1>}<p>{compact ? "Ventas, gastos y pendientes para decidir qué hacer hoy." : "Entiende qué vendes, cuánto queda y dónde actuar. Todos los importes están en dólares."}</p></div><div className="biz-header-actions"><button onClick={() => void refresh()} disabled={report.loading || operations.loading}><RefreshCw size={15}/>Actualizar</button>{compact ? <button onClick={() => onNavigate("management")}>Ver reporte completo <ArrowRight size={15}/></button> : <><button onClick={() => onNavigate("expenses")}><ReceiptText size={15}/>{readonly ? "Ver gastos" : "Registrar gastos"}</button><button disabled={!data} onClick={() => data && exportCsv(`resultados-${year}-${month}.csv`, [["Indicador", "Valor", "Alcance"], ["Período", label, dateBasis === "CREATED" ? "Fecha del pedido" : "Fecha de pago"], ["Categoría", category || "Todas", ""], ["Ventas de productos", data.revenue, "Sin envío"], ["Costo registrado de lo vendido", data.margin.cost, `${data.margin.unknownUnits} unidades sin costo`], ["Envíos cobrados", data.financial.shippingRevenue, "Solo en el total del negocio"], ["Gastos", data.financial.expenseTotal, "Todos los gastos registrados del período"], ["Resultado registrado", data.financial.result, "Vacío cuando faltan costos o se filtra una categoría"], ...data.months.map(m => [monthNames[m.month - 1], m.result, "Resultado mensual con registros actuales"])])}><Download size={15}/>Exportar</button></>}</div></div>
    {!compact && <div className="biz-period"><div className="biz-segments" role="group" aria-label="Accesos de período"><button onClick={() => setPeriod()}>Este mes</button><button onClick={() => setPeriod(true)}>Mes anterior</button><button onClick={() => setPeriod(false, true)}>Este año</button></div><label>Año<input type="number" min="2021" max="2100" value={year} onChange={e => { const v = Number(e.target.value); if (v >= 2021 && v <= 2100) setYear(v); }}/></label><label>Mes<select value={month} onChange={e => setMonth(Number(e.target.value))}><option value="0">Todo el año</option>{monthNames.map((name, i) => <option key={name} value={i + 1}>{name}</option>)}</select></label><label>Categoría<select value={category} onChange={e => setCategory(e.target.value)}><option value="">Todo el negocio</option>{taxonomy.data?.taxonomy.categories.map(c => <option key={c.key} value={c.key}>{c.name}</option>)}</select></label></div>}
    {(report.error || operations.error || message) && <div className="admin-alert" role="alert">{message || report.error?.message || operations.error?.message}<button onClick={() => void refresh()}>Reintentar</button></div>}
    {(report.loading || operations.loading) && <p className="biz-updating" role="status">Actualizando cifras…</p>}
    {data && <>
      <div className="biz-scope"><span><i/>{label}{!compact && category ? " · Categoría seleccionada" : " · Todo el negocio"}</span><small>Datos registrados · Ecuador</small></div>
      <div className="biz-kpis">
        <article className="biz-kpi"><div><span>Ventas de productos</span><ShoppingBag size={19}/></div><strong>{formatMoney(data.revenue)}</strong><small>{data.orderCount} pedidos pagados · {data.units} unidades</small><span className={`biz-change ${comparison?.revenueChange != null && comparison.revenueChange < 0 ? "negative" : ""}`}>{comparison?.revenueChange == null ? "Sin base anterior para comparar" : <>{comparison.revenueChange < 0 ? <ArrowDownRight size={14}/> : <ArrowUpRight size={14}/>} {Math.abs(comparison.revenueChange)}% frente al período comparable</>}</span></article>
        <article className="biz-kpi"><div><span>Gastos del negocio</span><ReceiptText size={19}/></div><strong>{formatMoney(data.financial.expenseTotal)}</strong><small>{data.financial.expenseCount} gastos registrados en el período</small><button className="biz-text-button" onClick={() => onNavigate("expenses")}>{readonly ? "Revisar gastos" : "Registrar o revisar"}<ArrowRight size={13}/></button></article>
        <article className={`biz-kpi biz-result ${data.financial.result !== null && data.financial.result < 0 ? "negative" : ""}`}><div><span>Resultado registrado</span><ChartNoAxesCombined size={19}/></div><strong>{data.financial.result === null ? "Por completar" : formatMoney(data.financial.result)}</strong><small>{data.financial.categoryFiltered ? "Consulta todo el negocio para incluir gastos" : !data.financial.completeCosts ? `${data.margin.unknownUnits} unidades vendidas sin costo registrado` : data.financial.result! < 0 ? "Pérdida con los datos registrados" : data.financial.expenseCount === 0 ? "Provisional: revisa los gastos pendientes" : "Ventas + envíos − costos − gastos"}</small><span className="biz-result-tag">{data.financial.result === null ? "Información pendiente" : "No incluye gastos sin registrar"}</span></article>
        <article className="biz-kpi"><div><span>Por cobrar ahora</span><CircleDollarSign size={19}/></div><strong>{pending === undefined ? "—" : formatMoney(pending)}</strong><small>Pedidos sin pago confirmado, incluye envío</small><button className="biz-text-button" onClick={() => onNavigate("orders", "status:PENDING_PAYMENT")}>Ver pedidos pendientes<ArrowRight size={13}/></button></article>
      </div>
      {!data.orderCount && !data.financial.expenseCount && <div className="biz-empty-note"><ChartNoAxesCombined size={22}/><div><b>Tu resumen se llenará con la operación real</b><p>Registra compras con su costo, confirma las ventas y agrega los gastos. Los gráficos se actualizarán con esos movimientos.</p></div><button onClick={() => onNavigate("purchases")}>Ver compras <ArrowRight size={14}/></button></div>}
      <div className="biz-grid-main"><article className="biz-card"><div className="biz-card-heading"><div><span className="kicker">EVOLUCIÓN</span><h2>Cómo cambia el negocio</h2></div><span className="biz-badge">{year}</span></div><TrendChart months={data.months} year={year} selected={month} onSelect={setMonth}/></article>
        <article className="biz-card biz-breakdown"><div className="biz-card-heading"><div><span className="kicker">DEL INGRESO AL RESULTADO</span><h2>¿Cuánto queda?</h2></div><span className="biz-badge">{label}</span></div><div className="biz-money-line"><span>Ventas de productos</span><b>{formatMoney(data.revenue)}</b></div><div className="biz-money-line"><span>− Costo de lo vendido</span><b>{formatMoney(data.margin.cost)}{!data.financial.completeCosts && " *"}</b></div><div className="biz-subtotal"><span>Ganancia bruta de productos</span><b>{data.margin.grossProfit === null ? data.units ? "Sin costos" : formatMoney(0) : formatMoney(data.margin.grossProfit)}</b></div><div className="biz-money-line"><span>+ Envíos cobrados</span><b>{data.financial.categoryFiltered ? "No distribuido" : formatMoney(data.financial.shippingRevenue)}</b></div><div className="biz-money-line"><span>− Gastos del negocio</span><b>{formatMoney(data.financial.expenseTotal)}</b></div><div className={`biz-total ${data.financial.result !== null && data.financial.result < 0 ? "negative" : ""}`}><span>Resultado registrado</span><strong>{data.financial.result === null ? "Pendiente" : formatMoney(data.financial.result)}</strong></div><p className="biz-caption">{data.margin.unknownUnits ? `* Faltan costos de ${data.margin.unknownUnits} unidades vendidas. La ganancia bruta mostrada cubre solo las ventas con costo conocido.` : "Las compras de mercadería se descuentan al venderse. Registra arriendo, publicidad, sueldos y transporte como gastos."} {data.financial.categoryFiltered && "Los gastos corresponden a todo el negocio y no se distribuyen entre categorías."}</p><button className="biz-text-button" onClick={() => onNavigate("expenses")}>Ver detalle de gastos <ArrowRight size={14}/></button></article></div>
      {!compact && <>
        <div className="biz-grid-equal"><article className="biz-card"><div className="biz-card-heading"><div><span className="kicker">QUÉ IMPULSA LAS VENTAS</span><h2>Ventas por categoría</h2></div>{category && <button onClick={() => setCategory("")}>Ver todas</button>}</div>{data.categories.length ? data.categories.slice(0, 8).map(c => <HorizontalBar key={c.key} label={c.name} value={c.revenue} max={Math.max(...data.categories.map(r => r.revenue), 1)} detail={`${c.units} unidades · Ver categoría →`} onClick={c.key === "uncategorized" ? undefined : () => setCategory(c.key)}/>) : <div className="biz-empty"><Package/><p>Aún no hay ventas en este período.</p></div>}<p className="biz-caption">Un producto puede estar en varias categorías. Estos importes no se suman entre sí.</p></article>
          <article className="biz-card"><div className="biz-card-heading"><div><span className="kicker">EN QUÉ SE GASTA</span><h2>Distribución de gastos</h2></div><button onClick={() => onNavigate("expenses")}>Ver detalle <ArrowRight size={14}/></button></div>{data.financial.expenseCategories.length ? data.financial.expenseCategories.map(c => <HorizontalBar key={c.category} label={expenseLabels[c.category] ?? c.category} value={c.amount} max={Math.max(...data.financial.expenseCategories.map(r => r.amount), 1)} color={c.category === "INVENTORY_LOSS" ? "red" : "amber"}/>) : <div className="biz-empty"><ReceiptText/><p>No hay gastos registrados. Eso todavía no confirma que el negocio no haya tenido gastos.</p>{!readonly && <button onClick={() => onNavigate("expenses")}>Registrar primer gasto</button>}</div>}</article></div>
        <article className="biz-card"><div className="biz-card-heading"><div><span className="kicker">PRODUCTOS Y RENTABILIDAD</span><h2>Qué se vende y qué deja</h2></div><button onClick={() => onNavigate("inventory")}>Ver reposición <ArrowRight size={14}/></button></div><div className="biz-product-ranking">{data.ranking.slice(0, 8).map((p, i) => <div className="biz-product-row" key={p.productId}><span className="biz-rank">{String(i + 1).padStart(2, "0")}</span><div className="biz-product-name"><b>{p.title}</b><small>{p.units} unidades vendidas</small></div><div><small>Ventas</small><b>{formatMoney(p.revenue)}</b></div><div className={p.grossProfit !== null && p.grossProfit < 0 ? "biz-negative" : ""}><small>Ganancia bruta {p.costComplete ? "" : "parcial"}</small><b>{p.grossProfit === null ? "Falta costo" : formatMoney(p.grossProfit)}</b></div><button onClick={() => onNavigate("movements", p.title)}>Ver recorrido <ArrowRight size={14}/></button></div>)}{!data.ranking.length && <p className="biz-empty">Los productos aparecerán cuando registres ventas pagadas.</p>}</div><p className="biz-caption">La ganancia por producto usa el costo guardado con la venta. Los gastos del negocio se descuentan en el resultado total.</p></article>
      </>}
    </>}
    {!compact && live && <>
      <div className="biz-section-divider"><div><span className="kicker">PARA ACTUAR HOY</span><h2>Pedidos, compras e inventario</h2></div><span className="biz-badge">Ahora · toda la tienda, sin filtros de período</span></div>
      <div className="biz-grid-equal"><article className="biz-card"><div className="biz-card-heading"><div><span className="kicker">PEDIDOS ABIERTOS</span><h2>Del pago a la entrega</h2></div><ShoppingBag size={21}/></div><div className="biz-order-flow">{live.orders.map((o, i) => <button key={o.status} onClick={() => onNavigate("orders", `status:${o.status}`)}><span className="biz-flow-step">{i + 1}</span><span><b>{orderLabels[o.status]}</b><small>{formatMoney(o.amount)} · incluye envío</small></span><strong>{o.count}</strong><ArrowRight size={14}/></button>)}</div><p className="biz-caption">Los pedidos cancelados, devueltos o completados no están en esta lista de trabajo.</p></article>
        <article className="biz-card"><div className="biz-card-heading"><div><span className="kicker">COMPRAS POR RECIBIR</span><h2>Mercadería en camino</h2></div><Truck size={22}/></div><div className="biz-purchase-total"><strong>{formatMoney(live.purchases.amount)}</strong><span>{live.purchases.count} compras confirmadas{live.purchases.overdue > 0 && <b className="biz-negative"> · {live.purchases.overdue} atrasadas</b>}</span></div>{live.purchases.rows.map(p => <button className="biz-purchase-row" key={p.id} onClick={() => onNavigate("purchases", p.number)}><span><b>{p.supplier}</b><small>{p.number} · {p.expectedOn ? `Esperada: ${p.expectedOn}` : "Fecha por confirmar"}</small></span><b>{formatMoney(p.total)}</b><ArrowRight size={14}/></button>)}{!live.purchases.count && <p className="biz-empty">No tienes compras pendientes de recepción.</p>}<p className="biz-caption">Este es el valor de las compras confirmadas. No representa pagos efectuados ni gastos del período.</p><button className="biz-text-button" onClick={() => onNavigate("purchases")}>Abrir compras <ArrowRight size={14}/></button></article></div>
      <div className="biz-grid-equal"><article className="biz-card"><div className="biz-card-heading"><div><span className="kicker">DINERO EN MERCADERÍA</span><h2>Inventario a costo</h2></div><Package size={22}/></div><div className="biz-purchase-total"><strong>{live.stock.unknownUnits === live.stock.units && live.stock.units > 0 ? "Por completar" : formatMoney(live.stock.knownValue)}</strong><span>{live.stock.units} unidades físicas · {live.stock.reserved} reservadas</span></div><p className="biz-caption">{live.stock.unknownUnits ? `${live.stock.unknownUnits} unidades no tienen costo y están fuera de este importe.` : "Valor según el costo registrado de los lotes. Incluye las unidades reservadas y vencidas aún en bodega."}</p>{data && !category && <StockRing healthy={data.inventory.length - data.lowStock} low={data.lowStock - data.outOfStock} empty={data.outOfStock}/>}<button className="biz-text-button" onClick={() => onNavigate("inventory")}>Revisar existencias y reposición <ArrowRight size={14}/></button></article>
        <article className="biz-card"><div className="biz-card-heading"><div><span className="kicker">EVITAR PÉRDIDAS</span><h2>Vencimientos que atender</h2></div><TriangleAlert size={22}/></div><div className="biz-risk-stats"><div><strong>{live.stock.expired.units}</strong><span>unidades vencidas</span></div><div><strong>{live.stock.expiring.units}</strong><span>vencen en 30 días</span></div></div>{live.stock.risks.map((p, i) => <button className="biz-purchase-row" key={`${p.sku}-${p.lot}-${i}`} onClick={() => onNavigate("warehouses", p.sku)}><span><b>{p.title}</b><small>Lote {p.lot} · {p.expiresOn}</small></span><b>{p.onHand} un.</b><ArrowRight size={14}/></button>)}{!live.stock.riskLots && <p className="biz-empty">No hay lotes con vencimiento registrado dentro de los próximos 30 días.</p>}<p className="biz-caption">Costo conocido en riesgo: {formatMoney(live.stock.expired.knownValue + live.stock.expiring.knownValue)}. {live.stock.expired.unknownUnits + live.stock.expiring.unknownUnits} unidades en riesgo sin costo. Es una alerta de inventario; las mermas efectivas se registran como gasto y ajuste de stock.</p></article></div>
    </>}
    {!compact && <details className="biz-method"><summary>Cómo leer estas cifras</summary><p>Las ventas incluyen pedidos pagados, en preparación, enviados y completados. Se excluyen pendientes, cancelados y devueltos según su estado actual. El resultado sigue esos estados y puede cambiar con una devolución posterior.</p><label>Fecha usada en las ventas <select value={dateBasis} onChange={e => setBasis(e.target.value)}><option value="CREATED">Creación del pedido</option><option value="PAID">Confirmación del pago</option></select></label><p>Los gastos usan su fecha registrada. El resultado es un control operativo con la información ingresada, no un balance contable ni saldo de caja. Incluye los envíos cobrados; registra transporte, comisiones e impuestos que correspondan como gastos. Las compras de mercadería se reconocen como costo al vender. Los pedidos antiguos sin fecha de pago no entran al filtrar por pago. Las comparaciones usan el mismo tiempo transcurrido.</p></details>}
    {data && <p className="biz-updated">Última actualización: {new Date(data.updatedAt).toLocaleString("es-EC", { timeZone: "America/Guayaquil" })}</p>}
  </section>;
}
