import { gql, useMutation } from "@apollo/client";
import { useState } from "react";
import { KeyRound } from "lucide-react";
const REQUEST = gql`mutation RequestPasswordReset($email: String!) { requestPasswordReset(email: $email) }`;
const RESET = gql`mutation ResetPassword($token: String!, $password: String!) { resetPassword(token: $token, password: $password) }`;
export function RecoveryForm({ token, onBack }: { token?: string; onBack: () => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [repeat, setRepeat] = useState(""); const [message, setMessage] = useState("");
  const [request, requesting] = useMutation(REQUEST); const [reset, resetting] = useMutation(RESET);
  return <form className="recovery-form" onSubmit={async (e) => { e.preventDefault(); setMessage(""); try { if (token) { if (password !== repeat) throw new Error("Las contraseñas no coinciden"); await reset({ variables: { token, password } }); setMessage("Contraseña actualizada. Ya puedes iniciar sesión."); } else { const r = await request({ variables: { email } }); setMessage(r.data.requestPasswordReset.deliveryAvailable ? "Si existe una cuenta activa con ese correo, recibirás un enlace válido por 30 minutos." : "La recuperación por correo aún no está configurada. Un administrador puede restablecer tu contraseña desde Usuarios y permisos."); } } catch (error) { setMessage(error instanceof Error ? error.message : "No pudimos completar la solicitud"); } }}><KeyRound/><h2>{token ? "Crea una contraseña nueva" : "Recuperar acceso"}</h2>{token ? <><label>Nueva contraseña<input autoComplete="new-password" required type="password" minLength={8} maxLength={120} value={password} onChange={(e) => setPassword(e.target.value)}/></label><label>Repetir contraseña<input autoComplete="new-password" required type="password" minLength={8} value={repeat} onChange={(e) => setRepeat(e.target.value)}/></label></> : <label>Correo de la cuenta<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} /></label>}{message && <p role="status">{message}</p>}<button className="primary-button" disabled={requesting.loading || resetting.loading}>{token ? "Guardar contraseña" : "Enviar enlace"}</button><button type="button" onClick={onBack}>Volver al acceso</button></form>;
}
